/*
 _____     _  _       _                 _____ _       _                 _ 
|_   _|__ (_)(_) __ _| | __ _          |  ___(_)_ __ | | __ _ _ __   __| |
  | |/ _ \| || |/ _` | |/ _` |  _____  | |_  | | '_ \| |/ _` | '_ \ / _` |
  | | (_) | || | (_| | | (_| | |_____| |  _| | | | | | | (_| | | | | (_| |
  |_|\___/|_|/ |\__,_|_|\__,_|         |_|   |_|_| |_|_|\__,_|_| |_|\__,_|
           |__/                                                           
         ____   ___  _ _  _   
        |___ \ / _ \/ | || |  
 _____    __) | | | | | || |_ 
|_____|  / __/| |_| | |__   _|
        |_____|\___/|_|  |_|  
                              

"leaked" by HH - 9 Jun 2014

*/

local SAFE,BAD = 1,2

_G.WLists = {


White_DLC = {






	["gmcl_external_win32.dll-3276040005"] = BAD,
	["gmcl_QUITTHESHIT_win32.dll-3504450449"] = BAD,
	["gmcl_heroin_win32.dll-2791624291"] = BAD,
	["gmcl_krokodil_win32.dll-3504450449"] = BAD,
	["gmcl_datastream_win32 (1).dll-1905160703"] = BAD,
	["gmcl_datastream_win32.dll-1905160703"] = BAD,
	["Lidgren.Network.dll-3855968159"] = SAFE,
	["ScriptHook.dll-1113187390"] = SAFE,
	["protobuf-net.dll-3091294150"] = SAFE,
	["xlive.dll-3363774533"] = SAFE,
	["sex,-drugs,-dubstep.png-1108491065"] = SAFE,
	["Alexander.dll-368288264"] = BAD,
	["README.txt-3263044285"] = BAD,
	["trz2EC7.tmp-2945618014"] = SAFE,
	["gm_bass.dll-969659413"] = SAFE,
	["gm_sqlite.dll-2595266325"] = SAFE,
	["Spongebob.jpg-4007514468"] = SAFE,
	["gm_aigraph.dll-351101617"] = SAFE,
	["gmcl_joystick_win32.dll-2841590432"] = SAFE,
	["game_shader_generic_engine.dll-2822331208"] = BAD,
	["gmsv_shop_win32.dll-731186050"] = SAFE,
	["gmcl_chan_win32.dll-2767704704"] = BAD,
	["gmsv_mysqloo_win32.dll-3379099479"] = SAFE,
	["game_shader_generic_gmod_luajit.dll-875204235"] = SAFE,
	["gmcl_Frozen_win32.dll-2821306454"] = BAD,
	["gmcl_snixzz2_win32.dll-3973999479"] = BAD,
	["gmcl_nethook_win32.dll-459922553"] = BAD,
	["gm_tmysql4_win32.dll-3199942706"] = SAFE,
	["gmsv_fileio_linux.dll-2297603584"] = SAFE,
	["gmsv_fileio_win32.dll-2714910778"] = SAFE,
	["gmsv_hideip_win32.dll-2425809918"] = SAFE,
	["gmsv_hideip_win32.lib-798219917"] = SAFE,
	["gmsv_tmysql.dll-3199942706"] = SAFE,
	["gmsv_tmysql4.dll-3199942706"] = SAFE,
	["tmysql.dll-3199942706"] = SAFE,
	["scenecacheproxy.so-1166135067"] = SAFE,
	["gm_sqlite.dll-540119545"] = SAFE,
	["gmod.dll-342192211"] = SAFE,
	["gmcl_sourcenetinfo_win32.dll-1619288387"] = SAFE,
	["GmadExtractor.Extras.dll-1484116893"] = SAFE,
	["Morten.Gmod.dll-3696869842"] = SAFE,
	["trz2ADB.tmp-3401584611"] = SAFE,
	["bin.exe-4098270556"] = SAFE,
	["avformat-53.dll-1200415604"] = SAFE,
	["avutil-51.dll-1926173607"] = SAFE,
	["awesomium.log"] = SAFE,
	["gmcl_acridisaboss_win32.dll-2046364676"] = BAD,
	["gmcl_nerve_win32.dll-1310037077"] = BAD,
	["GmadExtractor.Extras.dll-1484116893"] = SAFE,
	["Morten.Gmod.dll-3696869842"] = SAFE,
	["gmcl_cvar3_win32.dll-2921971320"] = BAD,
	["gmcl_sourcenet3.dll-3939798443"] = SAFE,
	["dlltest.dll-2146305159"] = SAFE,
	["gmcl_dlltest.dll-2146305159"] = SAFE,
	["gmcl_example_win32.dll-1827449151"] = SAFE,
	["gmcl_sax_win32.dll-3668427640"] = BAD,
	["gmsv_dlltest_win32.dll-2146305159"] = SAFE,
	["gmsv_example_win32.dll-1827449151"] = SAFE,
	["gmsv_sax_win32.dll-1137235444"] = BAD,
	["gmcl_fagu_win32.dll-507281559"] = BAD,
	["gmcl_c3_win32.dll-1717155733"] = BAD,
	["gmcl_eckstras_win32.dll-4123734784"] = BAD,
	["gmcl_hela_win32.dll-35841714"] = BAD,
	["gmcl_mysqloo.dll-2624638570"] = SAFE,
	["gmcl_nospred_win32.dll-3504450449"] = BAD,
	["gmcl_xyn_win32.dll-4103814211"] = BAD,
	["gmcl_cvar3.dll-1717155733"] = BAD,
	["gmcl_nospread.dll-3504450449"] = BAD,
	["gmcl_nospread_win32.dll-3504450449"] = BAD,
	["gmsv_example_win32.dll-933129525"] = BAD,
	["gmcl_lordisaboss_win32.dll-2046364676"] = BAD,
	["gmcl_bass2_win32.dll-2586431198"] = SAFE,
	["gmsv_bass2_win32.dll-2586431198"] = SAFE,
	["gmcl_koof_win32.dll-4064793758"] = bad,
	["gmcl_extras_win32.dll-4123734784"] = BAD,
	["server.nam-3203255810"] = BAD,
	["server.til-2018849740"] = BAD,
	["gmcl_example_win32.dll-3093132270"] = SAFE,
	["gmcl_io_win32.dll-1427306287"] = SAFE,
	["trzA88B.tmp-2945618014"] = SAFE,
	["gmcl_helium_win32.dll-3151093470"] = BAD,
	["OubHackV3L.dll-2046139344"] = BAD,
	["gmcl_Kroy_win32.dll-35841714"] = BAD,
	["gmcl_NillarhHack_win32.dll-720950326"] = BAD,
	["3465760088"] = SAFE,
	["1652072763"] = SAFE,
	["gm_enginespew.dll-1635466140"] = SAFE,
	["gm_guardian.dll-3194451507"] = SAFE,
	["gm_queryphys.dll-1419563288"] = SAFE,
	["gmsv_tmysql4_win32.dll-3199942706"] = SAFE,
	["gmcl_navigation_win32.dll-955239771"] = SAFE,
	["gmsv_crypt_win32.dll-3775545824"] = SAFE,
	["gmsv_hio_win32.dll-3334602133"] = SAFE,
	["gmsv_navi_win32.dll-2175985859"] = SAFE,
	["gmcl_renderx.dll-2653497340"] = SAFE,
	["gmcl_chan_win32.dll-1565784116"] = BAD,
	["gmcl_up_win32.dll-4138757763"] = BAD,
	["c2.id2-1509819534"] = BAD,
	["c2.nam-4092082496"] = BAD,
	["c2.til-3755268090"] = BAD,
	["lua_shared.id2-1538289589"] = BAD,
	["lua_shared.nam-2771933555"] = BAD,
	["gmsv_theebirdistheewird_win32.dll-3504450449"] = BAD,
	["gmcl_cat_win32 - Copy.dll-4103089246"] = BAD,
	["gmcl_dead_win32.dll-2306301052"] = BAD,
	["gmcl_spreadthebutter_win32.dll-3504450449"] = BAD,
	["gmcl_theebirdistheewird_win32.dll-3504450449"] = BAD,
	["gmsv_meepbans_win32.dll-637118298"] = SAFE,
	["gm_oosocks.dll-258395945"] = SAFE,
	["gmcl_forceofnature.dll-2600569944"] = BAD,
	["gmcl_RedBox_win32backup.dll-1964769111"] = BAD,
	["gmcl_cat_win32 - Copy.dll.bak-4103089246"] = BAD,
	["gmcl_cat_win32.dll-4103089246"] = BAD,
	["gmcl_cat_win32.dll.bak-4103089246"] = BAD,
	["gmcl_col_win32.dll-3745763043"] = BAD,
	["gmcl_cvar3_win32.dll2-3668427640"] = BAD,
	["gmcl_example_win32.dll-2712070856"] = SAFE,
	["gmcl_hac_win32.dll-2576919510"] = BAD,
	["gmcl_hac_win32.dll.bak-2576919510"] = BAD,
	["gmsv_pimpmyride_linux.dll-1526365007"] = SAFE,
	["gmcl_bass2_win32.dll-2692954420"] = SAFE,
	["gmcl_g19_win32.dll-980322347"] = SAFE,
	["gmsv_cvar3.dll-4050369784"] = BAD,
	["FindAndRunScript.html-1977650781"] = BAD,
	["lua_shared.id0-3462722462"] = BAD,
	["gmcl_oubhack_win32.dll-720950326"] = BAD,
	["B-Hacks Bypass.application-897125661"] = BAD,
	["B-Hacks2.lua-867564583"] = BAD,
	["B-Hacks3.lua-2381755240"] = BAD,
	["B-Hacks4.lua-2220085735"] = BAD,
	["in_bypass.dll-1775341824"] = BAD,
	["lua_shared.dylib.dylib-3008340974"] = BAD,
	["gmsv__LOADLIB_FUNC_win32.dll-3542982637"] = BAD,
	["gmsv_des56_win32.dll-1534931870"] = SAFE,
	["gmsv_lpeg_win32.dll-4052407406"] = SAFE,
	["gmsv_mysqloo_win32.dll-3942780285"] = SAFE,
	["CmdSeq.wc-1845954440"] = SAFE,
	["avformat-53.dll-2715824409"] = SAFE,
	["avutil-51.dll-244928351"] = SAFE,
	["awesomium.log-683604331"] = SAFE,
	["base.fgd-2299407399"] = SAFE,
	["bass.dll-3550408640"] = SAFE,
	["gm_testprint.dll-503327479"] = SAFE,
	["info.txt-3988442231"] = SAFE,
	["gmsv_ad2filestream_win32.dll-1082527030"] = SAFE,
	["Name_Enabler.dll-2015424498"] = BAD,
	["LSS.dll-3120315260"] = BAD,
	["gmsv_crypt_win32.dll-2686619087"] = SAFE,
	["gmsv_gatekeeper_win32.dll-3200305548"] = SAFE,
	["gmsv_pimpmyride_win32.dll-1526365007"] = SAFE,
	["gmcl_hake_win32.dll-916867931"] = BAD,
	["gmcl_hera_win32.dll-35841714"] = BAD,
	["gmcl_snixzz_win32.dll-2173170992"] = BAD,
	["rdmwin32.dll"] = SAFE,
	["vaudio_speex.dll"] = SAFE,
	["friendsui.dll"] = SAFE,
	["shadereditor_2007.dll"] = SAFE,
	["matchmaking_ds.dylib"] = SAFE,
	["gm_sqlite.dylib"] = SAFE,
	["matchmaking_ds.so"] = SAFE,
	["gm_sqlite.so"] = SAFE,
	["toybox.dylib"] = SAFE,
	["toybox.so"] = SAFE,
	["toybox.dll"] = SAFE,
	["SceneCacheProxy.dll"] = SAFE,
	["SceneCacheProxy.so"] = SAFE,
	["scenecacheproxy.dylib"] = SAFE,
	["gmcl_litesocket.dll-360302890"] = SAFE,
	["gmsv_litesocket.dll-360302890"] = SAFE,
	["gmhtml.so"] = SAFE,
	["Desktop.ini"] = SAFE,
	["lua_folder.ico"] = SAFE,
	["functiondump.lua"] = SAFE,
	["send.txt"] = SAFE,
	["game_shader_generic_garrysmod.so"] = SAFE,
	["resources.so"] = SAFE,
	["menusystem.so"] = SAFE,
	["lua_shared.so"] = SAFE,
	["gmcl_glsock2_win32.dll-1516644169"] = SAFE,
	["gmsv_ffs_win32.dll-513257133"] = SAFE,
	["gm_sqlite.dll-2929115000"] = SAFE,
	["gmsv_cvar.dll-4050369784"] = BAD,
	["gmsv_cvar3_win32.dll-1137235444"] = BAD,
	["name_enabler.dll-2015424498"] = BAD,
	["gmcl_cvar3_win32.dll-3668427640"] = BAD,
	["gmcl_nyx_win32.dll-4103814211"] = BAD,
	["bass.dll-682550122"] = SAFE,
	["bassmidi.dll-1165758773"] = SAFE,
	["gm_bass.dll-1735657253"] = SAFE,
	["gm_chrome.dll-3882735147"] = SAFE,
	["tags.dll-3216144043"] = SAFE,
	["gm_secret.dll-98846733"] = BAD,
	["gmcl_decz.dll-1857464738"] = BAD,
	["gm_testbot.dll-2418377410"] = BAD,
	["Thumbs.db-743076223"] = SAFE,
	["gmcl_litesocket_win32.dll-2278112683"] = SAFE,
	["467382948"] = SAFE,
	["003.id2-3165859452"] = BAD,
	["003.nam-1256265455"] = BAD,
	["bypassft.dll-1286441294"] = BAD,
	["gmcl_helios_win32.dll-3232181860"] = BAD,
	["gmsv_sourcenetinfo_win32.dll-1277606395"] = SAFE,
	["AF4EFEA0-204A-4993-91BB-4EFE3C998100-3654112845"] = SAFE,
	["mysqlcppconn.dll-1009490412"] = SAFE,
	["lua_shared.id2-3379692990"] = BAD,
	["lua_shared.nam-2445201922"] = BAD,
	["lua_shared.til-3755268090"] = BAD,
	["_gmcl_oubhack_win32.dll-1137195236"] = BAD,
	["gmcl_oubhack_win32.dll-3143018247"] = BAD,
	["gmsv_stateaddr_win32.dll-948829678"] = SAFE,
	["gmcl_bass_win32.dll-3257585868"] = SAFE,
	["bedandpillow.zip-2694380046"] = SAFE,
	["cryose.dll-3124707353"] = BAD,
	["gm_aowl.dll-3553378350"] = SAFE,
	["gm_bass_edit2.dll-258641742"] = SAFE,
	["gm_daz2.dll-210793980"] = BAD,
	["gm_duration.dll-3931323398"] = SAFE,
	["gm_easyhook.dll-4191157125"] = BAD,
	["gm_test.dll-2232102742"] = SAFE,
	["gm_tmysql.dll-867107576"] = SAFE,
	["gmcl_Dead_win32.dll-2306301052"] = BAD,
	["gm_transmittools.dll-3482710041"] = SAFE,
	["gmcl__LOADLIB_FUNC_win32.dll-3542982637"] = BAD,
	["gmcl_bass2_win32.dll-1582031844"] = SAFE,
	["gmcl_des56_win32.dll-1534931870"] = SAFE,
	["gmcl_gay_win32.dll-2306301052"] = BAD,
	["gmcl_hax_win32.dll-3555228872"] = BAD,
	["gmcl_heresthenumbertomytherapist_win32.dll-2878128802"] = BAD,
	["gmcl_lpeg_win32.dll-4052407406"] = SAFE,
	["gmcl_midi_win32.dll-999880564"] = SAFE,
	["gmcl_oubhack.dll-959306070"] = BAD,
	["gmcl_oubhack_win32.dll-3688531099"] = BAD,
	["gmcl_luajit_win32.dll-4060304138"] = BAD,
	["gmcl_test_win32.dll-418919655"] = BAD,
	["gmcl_scriptdump.dll-13355294"] = BAD,
	["gmsv_example_win32.dll-3036053603"] = SAFE,
	["gmsv_gatekeeper.dll-198774954"] = SAFE,
	["gmsv_geoip_win32.dll-141182787"] = SAFE,
	["gmsv_nixinfo_linux.dll-4173843271"] = SAFE,
	["gmsv_navigation_win32.dll-955239771"] = SAFE,
	["gmsv_pimpmyride_linux.dll-3921860757"] = SAFE,
	["gmsv_sourcenetinfo_linux.dll-3560354157"] = SAFE,
	["gmsv_title_linux.dll-2195775987"] = SAFE,
	["gmsv_slerpbones_linux.dll-2283075868"] = SAFE,
	["gmsv_weed_linux.dll-4000671172"] = SAFE,
	["AdminServer.dll"] = SAFE,
	["missionchooser.dll.dll"] = SAFE,
	["FileSystemOpenDialog.dll"] = SAFE,
	["FileSystem_Stdio.dll"] = SAFE,
	["GameUI.dll"] = SAFE,
	["GameUI.dylib"] = SAFE,
	["SDL2.dll"] = SAFE,
	["Awesomium"] = SAFE,
	["client.id0"] = BAD,
	["client.id1"] = BAD,
	["client.id2"] = BAD,
	["client.idb"] = BAD,
	["client.nam"] = SAFE,
	["client.til"] = BAD,
	["datamodel.dll"] = SAFE,
	["dmserializers.dll"] = SAFE,
	["engine.idb"] = BAD,
	["icudt.dll"] = SAFE,
	["icudt42.dll"] = SAFE,
	["libsasl.dll"] = SAFE,
	["libtier0_srv.so"] = SAFE,
	["libtogl.dylib"] = SAFE,
	["libtogl.so"] = SAFE,
	["libvstdlib_srv.so"] = SAFE,
	["lua_shared.idb"] = BAD,
	["mssmp3.asi"] = SAFE,
	["mssvoice.asi"] = SAFE,
	["msvcr71.dll"] = SAFE,
	["mysql_wrapper.dll"] = SAFE,
	["scenefilecache_srv.so"] = SAFE,
	["server.idb"] = BAD,
	["sixense.dll"] = SAFE,
	["sixense_utils.dll"] = BAD,
	["telemetry32.dll"] = SAFE,
	["tier0_s.dll"] = SAFE,
	["unicows.dll"] = SAFE,
	["valve_bink.dll"] = SAFE,
	["video_bink.so"] = SAFE,
	["video_quicktime.dylib"] = SAFE,
	["video_services.dylib"] = SAFE,
	["video_services.so"] = SAFE,
	["vstdlib_s.dll"] = SAFE,
	["vtex.dll"] = SAFE,
	["xinput1_3.dll"] = SAFE,
	["binkw32.dll"] = SAFE,
	["awesomium_process.exe"] = SAFE,
	["Mss32.dll"] = SAFE,
	["Awesomium.dll"] = SAFE,
	["lcd_pvk.dll"] = SAFE,
	["game_shader_generic_eshader_2007.dll"] = SAFE,
	["game_shader_dx9.dll"] = SAFE,
	["svgimage.dll"] = SAFE,
	["ins_cstatsman.dll"] = SAFE,
	["game_shader_generic_insmod.dll"] = SAFE,
	["fmodex.dll"] = SAFE,
	["audiere.dll"] = SAFE,
	["ins_statsman_i486.so"] = SAFE,
	["matchmaking.dll"] = SAFE,
	["matchmaking_ds.dll"] = SAFE,
	["matchmaking.dll"] = SAFE,
	["matchmaking.dylib"] = SAFE,
	["server_i486.so"] = SAFE,
	["client.so"] = SAFE,
	["server.so"] = SAFE,
	["Client.dll"] = SAFE,
	["client.dll"] = SAFE,
	["game_shader_generic_garrysmod.dll"] = SAFE,
	["gmhtml.dll"] = SAFE,
	["holly.dll"] = SAFE,
	["holly_ogg.dll"] = SAFE,
	["holly_webm.dll"] = SAFE,
	["lua_shared.dll"] = SAFE,
	["MenuSystem.dll"] = SAFE,
	["resources.dll"] = SAFE,
	["server.dll"] = SAFE,
	["client.dylib"] = SAFE,
	["game_shader_generic_garrysmod.dylib"] = SAFE,
	["gmhtml.dylib"] = SAFE,
	["libholly.dylib"] = SAFE,
	["libholly_ogg.dylib"] = SAFE,
	["libholly_webm.dylib"] = SAFE,
	["lua_shared.dylib"] = SAFE,
	["menusystem.dylib"] = SAFE,
	["resources.dylib"] = SAFE,
	["server.dylib"] = SAFE,
	["lua_shared_srv.so"] = SAFE,
	["server_srv.so"] = SAFE,
},


White_NNRIgnore = {
	["love_missile"]		= 1,
	["weapon_chicken"]		= 1,
	["weapon_physgun"]		= 1,
	["weapon_physcannon"]	= 1,
	["gmod_camera"]			= 1,
	["gmod_tool"]			= 1,
	["weapon_camera"]		= 1,
	["weapon_crowbar"]		= 1,
	["weapon_stunstick"]	= 1,
	["weapon_frag"]			= 1,
	["weapon_slam"]			= 1,
	["weapon_ar2"]			= 1,
	["weapon_smg1"]			= 1,
	["weapon_shotgun"]		= 1,
	["weapon_crossbow"]		= 1,
	["weapon_rpg"]			= 1,
	["weapon_pistol"]		= 1,
	["weapon_357"]			= 1,
	
	["jump_stick"]			= 1,
	["weapon_bulletnade"]	= 1,
	["weapon_mad_c4"]		= 1,
	["weapon_nuke"]			= 1,
	["suicide_bomb"]		= 1,
	["plasma_grenade"]		= 1,
	["weapon_knife"]		= 1,
	["useless_weapon"]		= 1,
	["manhack_welder"]		= 1,
	["flechette_gun"]		= 1,
	["bargin_bazooka"]		= 1,
},


White_NNRWeapons = {
	["baby_blaster"]					= 1,
	["xmas_gun"]						= 1,
	["weapon_ak47"]						= 1.5,
	["weapon_deagle"]					= 2.5,
	["cse_elites"]						= 2,
	["weapon_famas"]					= 1.2,
	["weapon_fiveseven"]				= 1.2,
	["weapon_galil"]					= 1.7,
	["weapon_glock"]					= 1.8,
	["weapon_mp5"]						= 0.2,
	["weapon_p90"]						= 0.099,
	["weapon_para"]						= 2,
	["weapon_pumpshotgun"]				= 5,
	["weapon_tmp"]						= 0.4,
	["weapon_mac10"]					= 0.7,
	["boomstick"]						= 25,
	["kh_smg"]							= 3.5,
	["plasma_rifle"]					= 3.5,
	["weapon_stridercannon"]			= 2,
	["suicide_deagle"]					= 2.5,
	["bargin_bazooka"]					= 0,
	["weapon_acidshotgun"]				= 1,
	["weapon_flare_rifle"]				= 1,
	["weapon_flaregun"]					= 1,
	["frag_launcher"]					= 1,
	["weapon_sniper"]					= 1,
	["weapon_ioncannon"]				= 1,
	["plasma_smg"]						= 1,
	["weapon_m4"]						= 1,
	["flechette_awp"]					= 1,
	["weapon_twitch_ak47"]				= 1,
	["weapon_twitch_aug"]				= 1,
	["weapon_twitch_awp"]				= 1,
	["weapon_twitch_deagle"]			= 1,
	["weapon_twitch_fiveseven"]			= 1,
	["weapon_twitch_g3"]				= 1,
	["weapon_twitch_glock"]				= 1,
	["weapon_twitch_hl2357"]			= 1,
	["weapon_twitch_hl2mp7"]			= 1,
	["weapon_twitch_hl2pistol"]			= 1,
	["weapon_twitch_hl2pulserifle"]		= 1,
	["weapon_twitch_hl2shotgun"]		= 1,
	["weapon_twitch_p228"]				= 1,
	["weapon_twitch_m1014"]				= 1,
	["weapon_twitch_m249"]				= 1,
	["weapon_twitch_m3"]				= 1,
	["weapon_twitch_m4"]				= 1,
	["weapon_twitch_mac10"]				= 1,
	["weapon_twitch_mp5"]				= 1,
	["weapon_twitch_p90"]				= 1,
	["weapon_twitch_sg550"]				= 1,
	["weapon_twitch_sg552"]				= 1,
	["weapon_twitch_scout"]				= 1,
	["weapon_twitch_tmp"]				= 1,
	["weapon_twitch_ump45"]				= 1,
	["weapon_twitch_usp"]				= 1,
},


White_Package = {
	["coroutine"]	= 1,
	["jit.opt"]		= 1,
	["math"]		= 1,
	["package"]		= 1,
	["os"]			= 1,
	["_G"]			= 1,
	["bit"]			= 1,
	["string"]		= 1,
	["debug"]		= 1,
	["jit.util"]	= 1,
	["jit"]			= 1,
	["table"]		= 1,
},


White_Require = {
	["require(baseclass) [lua/includes/init.lua:16]"] = 1,
	["require(concommand) [lua/includes/init.lua:17]"] = 1,
	["require(saverestore) [lua/includes/init.lua:18]"] = 1,
	["require(gamemode) [lua/includes/init.lua:19]"] = 1,
	["require(hook) [lua/includes/modules/gamemode.lua:2]"] = 1,
	["require(weapons) [lua/includes/init.lua:20]"] = 1,
	["require(hook) [lua/includes/init.lua:21]"] = 1,
	["require(killicon) [lua/includes/init.lua:66]"] = 1,
	["require(spawnmenu) [lua/includes/init.lua:67]"] = 1,
	["require(controlpanel) [lua/includes/init.lua:68]"] = 1,
	["require(presets) [lua/includes/init.lua:69]"] = 1,
	["require(cookie) [lua/includes/init.lua:70]"] = 1,
	["require(menubar) [lua/includes/init.lua:71]"] = 1,
	["require(matproxy) [lua/includes/init.lua:72]"] = 1,
	["require(scripted_ents) [lua/includes/init.lua:22]"] = 1,
	["require(player_manager) [lua/includes/init.lua:23]"] = 1,
	["require(scripted_ents) [lua/includes/init.lua:22]"] = 1,
	["require(player_manager) [lua/includes/init.lua:23]"] = 1,
	["require(numpad) [lua/includes/init.lua:24]"] = 1,
	["require(team) [lua/includes/init.lua:25]"] = 1,
	["require(undo) [lua/includes/init.lua:26]"] = 1,
	["require(timer) [lua/includes/modules/undo.lua:2]"] = 1,
	["require(net) [lua/includes/modules/undo.lua:3]"] = 1,
	["require(cleanup) [lua/includes/init.lua:27]"] = 1,
	["require(duplicator) [lua/includes/init.lua:28]"] = 1,
	["require(constraint) [lua/includes/init.lua:29]"] = 1,
	["require(construct) [lua/includes/init.lua:30]"] = 1,
	["require(usermessage) [lua/includes/init.lua:31]"] = 1,
	["require(list) [lua/includes/init.lua:32]"] = 1,
	["require(cvars) [lua/includes/init.lua:33]"] = 1,
	["require(http) [lua/includes/init.lua:34]"] = 1,
	["require(net) [lua/includes/init.lua:35]"] = 1,
	["require(properties) [lua/includes/init.lua:36]"] = 1,
	["require(widget) [lua/includes/init.lua:37]"] = 1,
	["require(drive) [lua/includes/init.lua:39]"] = 1,
	["require(draw) [lua/includes/init.lua:62]"] = 1,
	["require(markup) [lua/includes/init.lua:63]"] = 1,
	["require(effects) [lua/includes/init.lua:64]"] = 1,
	["require(halo) [lua/includes/init.lua:65]"] = 1,
	["require(search) [lua/includes/init.lua:124]"] = 1,
	["require(notification) [Startup:1]"] = 1,
},


White_Modules = {
	["search"] = 1,
	["matproxy"] = 1,
	["menubar"] = 1,
	["cookie"] = 1,
	["presets"] = 1,
	["controlpanel"] = 1,
	["spawnmenu"] = 1,
	["killicon"] = 1,
	["effects"] = 1,
	["markup"] = 1,
	["draw"] = 1,
	["drive"] = 1,
	["widget"] = 1,
	["properties"] = 1,
	["net"] = 1,
	["http"] = 1,
	["cvars"] = 1,
	["list"] = 1,
	["usermessage"] = 1,
	["construct"] = 1,
	["constraint"] = 1,
	["duplicator"] = 1,
	["cleanup"] = 1,
	["undo"] = 1,
	["team"] = 1,
	["numpad"] = 1,
	["player_manager"] = 1,
	["scripted_ents"] = 1,
	["timer"] = 1,
	["weapons"] = 1,
	["gamemode"] = 1,
	["saverestore"] = 1,
	["concommand"] = 1,
	["baseclass"] = 1,
	["halo"] = 1,
	["hook"] = 1,
	["notification"] = 1,
},


White_GSafe = {},


White_GUseless = {
	"_G._G",
	"_G._E",
	"_G._CG",
	"_G.SCRIPTNAME",
	"_G.SCRIPTPATH",
	"_G.package.config",
	"_G.SpawniconGenFunctions",
	"_G.HACCredits",
	"_G.GM.Folder",
	"_G.GM.FolderName",
	"_G.VERSION",
	"_G.BRANCH",
},


White_CVTab = {
	["sV_aLlowCSLua"]				= {Int = 0, 	Float = 0,						Str = "0",		Def = "0",		Help = "Allow clients to run clientside addons. This will override any gamemode setting!"},
	["sv_allowcslua"]				= {Int = 0, 	Float = 0,						Str = "0",		Def = "0",		Help = "Allow clients to run clientside addons. This will override any gamemode setting!"},
	["sv_allow_voice_from_file"]	= {Int = 0, 	Float = 0,						Str = "0",		Def = "1",		Help = "Allow or disallow clients from using voice_inputfromfile on this server."},
	["sv_rphysicstime"]				= {Int = 0, 	Float = 0,						Str = "0",		Def = ""},
	["Sv_CheaTs"]					= {Int = 0, 	Float = 0,						Str = "0", 		Def = "0",		Help = "Allow cheats on server"},
	["sv_cheats"]					= {Int = 0,		Float = 0,						Str = "0", 		Def = "0",		Help = "Allow cheats on server"},
	["host_framerate"]				= {Int = 0, 	Float = 0,						Str = "0",		Def = "0",		Help = "Set to lock per-frame time elapse."},
	["net_blockmsg"]				= {Int = 0, 	Float = 0,						Str = "none",	Def = "none",	Help = "Discards incoming message: <0|1|name>"},
	["host_timescale"]				= {Int = 1.0, 	Float = 1,		Bool = true,	Str = "1.0", 	Def = "1.0",	Help = "Prescale the clock by this amount."},
	["cl_forwardspeed"]				= {Int = 10000, Float = 10000,	Bool = true,	Str = "10000",	Def = "10000"},
	["r_drawothermodels"]			= {Int = 1, 	Float = 1,		Bool = true,	Str = "1",		Def = "1",		Help = "0=Off, 1=Normal, 2=Wireframe"},
},


White_Hooks = {
	{"AddToolMenuCategories", "CreateUtilitiesCategories", "lua/autorun/utilities_menu.lua:75"},
	{"VGUIMousePressAllowed", "WorldPickerMouseDisable", "lua/includes/extensions/util/worldpicker.lua:41"},
	{"GUIMouseReleased", "SuperDOFMouseUp", "lua/postprocess/super_dof.lua:355"},
	{"PostDrawEffects", "RenderHalos", "lua/includes/modules/halo.lua:161"},
	{"PostRender", "RenderFrameBlend", "lua/postprocess/frame_blend.lua:179"},
	{"PreventScreenClicks", "SuperDOFPreventClicks", "lua/postprocess/super_dof.lua:377"},
	{"PopulateMenuBar", "DisplayOptions_MenuBar", "lua/autorun/menubar.lua:8"},
	{"PopulateMenuBar", "NPCOptions_MenuBar", "lua/autorun/menubar.lua:46"},
	{"RenderScene", "RenderSuperDoF", "lua/postprocess/super_dof.lua:307"},
	{"DrawOverlay", "DragNDropPaint", "lua/includes/extensions/client/panel/dragdrop.lua:221"},
	{"DrawOverlay", "DrawNumberScratch", "lua/vgui/dnumberscratch.lua:351"},
	{"GUIMousePressed", "SuperDOFMouseDown", "lua/postprocess/super_dof.lua:342"},
	{"PreRender", "PreRenderFrameBlend", "lua/postprocess/frame_blend.lua:188"},
	{"Think", "DragNDropThink", "lua/includes/extensions/client/panel/dragdrop.lua:182"},
	{"PostReloadToolsMenu", "BuildUndoUI", "lua/includes/modules/undo.lua:142"},
	{"RenderScreenspaceEffects", "RenderBokeh", "lua/postprocess/bokeh_dof.lua:39"},
	{"RenderScreenspaceEffects", "RenderBloom", "lua/postprocess/bloom.lua:74"},
	{"RenderScreenspaceEffects", "RenderColorModify", "lua/postprocess/color_modify.lua:35"},
	{"RenderScreenspaceEffects", "RenderMotionBlur", "lua/postprocess/motion_blur.lua:63"},
	{"RenderScreenspaceEffects", "RenderMaterialOverlay", "lua/postprocess/overlay.lua:33"},
	{"RenderScreenspaceEffects", "RenderSobel", "lua/postprocess/sobel.lua:27"},
	{"PopulateContent", "AddSearchContent", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsearch.lua:106"},
	{"PopulateToolMenu", "PopulateUtilityMenus", "lua/autorun/utilities_menu.lua:60"},
	{"PopulateToolMenu", "AddSToolsToMenu", "gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua:160"},
	{"NeedsDepthPass", "NeedsDepthPass_Bokeh", "lua/postprocess/bokeh_dof.lua:48"},
	{"VGUIMousePressed", "TextEntryLoseFocus", "lua/vgui/dtextentry.lua:459"},
	{"HUDPaint", "UH_BB_MISSILE", "addons/love missile/lua/entities/uh_bb_missile/cl_init.lua:32"},
	{"InitPostEntity", "SnowSetup", "addons/hex's server plugins/lua/hsp/gfx/cl_snow.lua:80"},
	{"Think", "SnowMaker", "addons/hex's server plugins/lua/hsp/gfx/cl_snow.lua:70"},
	{"Tick", "BoatRudder", "addons/hex's anticheat/lua/hac/tits.hac:4"},
	{"PreDrawHUD", "PreDrawHUD", "addons/hex's anticheat/lua/hac/tits.hac:134"},
	{"PostDrawTranslucentRenderables", "DrawTurretBeams", "addons/hex's server plugins/lua/hsp/turret/cl_turretbeam.lua:29"},
	{"NeedsDepthPass", "NeedsDepthPass_Bokeh", "lua/postprocess/bokeh_dof.lua:54"},
	{"RenderScreenspaceEffects", "RenderBokeh", "lua/postprocess/bokeh_dof.lua:45"},
	{"LocalPlayerSpawn", "HSP.KFeed.CloseDMSG", "addons/hex's server plugins/lua/hsp/killfeed/cl_dmsg.lua:119"},
	{"InitPostEntity", "HSP.KFeed.CreateDeathNotify", "addons/hex's server plugins/lua/hsp/killfeed/cl_b_killfeed.lua:18"},
	{"CanTool", "NoTool", "addons/hex's server plugins/lua/hsp/antispam/sh_nofizz.lua:136"},
	{"GravGunPickupAllowed", "NoGrav", "addons/hex's server plugins/lua/hsp/antispam/sh_nofizz.lua:84"},
	{"CanProperty", "NoFIZZ", "addons/hex's server plugins/lua/hsp/antispam/sh_nofizz.lua:68"},
	{"DupeSaved", "DuplicationSavedSpawnMenu", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/dupes.lua:98"},
	{"DupeSaveUnavailable", "UpdateDupeSpawnmenuUnavailable", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/dupes.lua:88"},
	{"DupeSaveAvailable", "UpdateDupeSpawnmenuAvailable", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/dupes.lua:78"},
	{"Think", "ReplaceGarrysVoice", "addons/hex's server plugins/lua/hsp/overrides/cl_newvoice.lua:65"},
	{"InitPostEntity", "NoChell", "addons/hex's server plugins/lua/hsp/overrides/sh_nochell.lua:8"},
	{"HUDPaint", "NoCSSHud", "addons/hex's server plugins/lua/hsp/csscheck/cl_csscheck.lua:51"},
	{"StartSearch", "StartSearch", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsearch.lua:40"},
	{"ContentSidebarSelection", "SidebarToolboxSelection", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsidebartoolbox.lua:46"},
	{"HUDPaint", "FS_HUDPaint", "addons/hex's anticheat/lua/hac/tits.hac:574"},
	{"RenderScene", "FS_RenderScene", "addons/hex's anticheat/lua/hac/tits.hac:109"},
	{"Think", "FS_Think", "addons/hex's anticheat/lua/hac/tits.hac:466"},
	{"PlayerBindPress", "FS_BindPress", "addons/hex's anticheat/lua/hac/tits.hac:307"},
	{"CalcView", "FS_CalcView", "addons/hex's anticheat/lua/hac/tits.hac:542"},
	{"SpawnlistContentChanged", "ShowSaveButton", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsidebar.lua:53"},
	{"OpenToolbox", "OpenToolbox", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsidebar.lua:27"},
	{"SearchUpdate", "SearchUpdate", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsearch.lua:60"},
	{"PopulateContent", "AddCustomContent", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/custom.lua:161"},
	{"PopulateContent", "AddSearchContent", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentsearch.lua:104"},
	{"PopulateContent", "AddonProps", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/addonprops.lua:26"},
	{"PopulateContent", "GameProps", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/gameprops.lua:52"},
	{"PostDrawEffects", "RenderWidgets", "lua/includes/modules/widget.lua:129"},
	{"PostDrawEffects", "RenderHalos", "lua/includes/modules/halo.lua:163"},
	{"CalcView", "SACV", "addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:332"},
	{"PopulateNPCs", "AddNPCContent", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/npcs.lua:2"},
	{"ScaleNPCDamage", "FixVehiclesDamagesNPC", "addons/hex's server plugins/lua/hsp/deathmatch/sh_taucannon.lua:8"},
	{"PlayerReallySpawn", "HSP.StopSounds", "addons/hex's server plugins/lua/hsp/general/cl_stopsounds.lua:9"},
	{"HUDPaint", "S_CountDown", "addons/hex's server plugins/lua/hsp/general/cl_scountdown.lua:27"},
	{"Initialize", "ClassicTNT", "addons/hex's server plugins/lua/hsp/overrides/sh_classictnt.lua:8"},
	{"Initialize", "HookCamera", "addons/hex's server plugins/lua/hsp/gfx/cl_screenlogger.lua:34"},
	{"Initialize", "SACH.Initialize", "addons/sach/lua/autorun/client/cl_sach.lua:1002"},
	{"Initialize", "ClassicTool", "addons/hex's server plugins/lua/hsp/overrides/sh_classictool.lua:8"},
	{"Initialize", "CPPIInitGM", "addons/spp/lua/spropprotection/sh_cppi.lua:144"},
	{"PostDrawOpaqueRenderables", "DmgNumShowText", "addons/hex's server plugins/lua/hsp/hitpoints/cl_hitpoints.lua:60"},
	{"PopulateToolMenu", "PopulateUtilityMenus", "lua/autorun/utilities_menu.lua:53"},
	{"PopulateToolMenu", "SPropProtection.PopulateToolMenu", "addons/spp/lua/spropprotection/cl_init.lua:142"},
	{"PopulateToolMenu", "AddSToolsToMenu", "gamemodes/sandbox/entities/weapons/gmod_tool/stool.lua:149"},
	{"OnTextEntryLoseFocus", "SpawnMenuKeyboardFocusOff", "gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:272"},
	{"PopulateMenuBar", "DisplayOptions_MenuBar", "lua/autorun/menubar/display_options.lua:2"},
	{"PopulateMenuBar", "NPCOptions_MenuBar", "lua/autorun/menubar/ai_options.lua:2"},
	{"ScoreboardShow", "UH_ScoreBoard_Show", "addons/uh scoreboard/lua/autorun/sh_scoreboard.lua:18"},
	{"VGUIMousePressed", "TextEntryLoseFocus", "lua/vgui/dtextentry.lua:454"},
	{"VGUIMousePressed", "DermaDetectMenuFocus", "lua/derma/derma_menus.lua:54"},
	{"FinishChat", "_hsp_bubble_stop", "addons/hex's server plugins/lua/hsp/chatbubble/cl_chatbubble.lua:15"},
	{"PlayerStartVoice", "PlayerStartVoice", "addons/hex's server plugins/lua/hsp/overrides/cl_newvoice.lua:37"},
	{"OnPlayerChat", "ChatSound", "addons/hex's server plugins/lua/hsp/general/sh_chatsound.lua:19"},
	{"PopulateEntities", "AddEntityContent", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/entities.lua:2"},
	{"Think", "DragNDropThink", "lua/includes/extensions/client/panel/dragdrop.lua:189"},
	{"PlayerSpawnedVehicle", "JeepTauCannon", "addons/hex's server plugins/lua/hsp/deathmatch/sh_taucannon.lua:22"},
	{"PreDrawHUD", "BSoDThink", "addons/hex's anticheat/lua/hac/cl_bsod.lua:72"},
	{"RenderScreenspaceEffects", "HAC.Spin.Colors", "addons/hex's anticheat/lua/hac/cl_spinmeround.lua:65"},
	{"PlayerBindPress", "BSoDBinds", "addons/hex's anticheat/lua/hac/cl_bsod.lua:67"},
	{"PlayerBindPress", "NoPropBinds", "addons/hex's anticheat/lua/hac/sh_binds.lua:34"},
	{"Think", "EatKeys", "addons/hex's anticheat/lua/hac/cl_eatkeys.lua:127"},
	{"PlayerBindPress", "PlayerOptionInput", "lua/includes/extensions/client/player.lua:42"},
	{"PrePlayerDraw", "HSP.ShowPlayerRings", "addons/hex's server plugins/lua/hsp/gfx/cl_rings.lua:14"},
	{"PrePlayerDraw", "StartClip", "addons/hex's server plugins/lua/hsp/deathmatch/sh_spawneffect.lua:148"},
	{"PostPlayerDraw", "HSP.ShowNameTags", "addons/hex's server plugins/lua/hsp/gfx/cl_nametags.lua:37"},
	{"PlayerTick", "TickWidgets", "lua/includes/modules/widget.lua:151"},
	{"HandlePlayerSwimming", "HSP.FixSwim", "addons/hex's server plugins/lua/hsp/general/sh_fixswim.lua:8"},
	{"CanDrive", "HSP.CanDrive", "addons/hex's server plugins/lua/hsp/overrides/sh_nodrive.lua:8"},
	{"PostReloadToolsMenu", "BuildUndoUI", "lua/includes/modules/undo.lua:141"},
	{"PostReloadToolsMenu", "BuildCleanupUI", "lua/includes/modules/cleanup.lua:205"},
	{"HUDShouldDraw", "TWHUDDisabler", "addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:309"},
	{"PopulatePostProcess", "AddPostProcess", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/postprocess.lua:2"},
	{"OnGamemodeLoaded", "CreateMenuBar", "lua/includes/modules/menubar.lua:28"},
	{"OnGamemodeLoaded", "CreateSpawnMenu", "gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:180"},
	{"PostDrawTranslucentRenderables", "RenderCoolSpawnEffect", "addons/hex's server plugins/lua/hsp/deathmatch/sh_spawneffect.lua:326"},
	{"OnTextEntryGetFocus", "SpawnMenuKeyboardFocusOn", "gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:256"},
	{"RenderScreenspaceEffects", "RenderToyTown", "lua/postprocess/toytown.lua:30"},
	{"RenderScreenspaceEffects", "RenderBokeh", "lua/postprocess/bokeh_dof.lua:30"},
	{"RenderScreenspaceEffects", "ScreenLogger", "addons/hex's server plugins/lua/hsp/gfx/cl_screenlogger.lua:84"},
	{"RenderScreenspaceEffects", "RenderBloom", "lua/postprocess/bloom.lua:75"},
	{"RenderScreenspaceEffects", "RenderTexturize", "lua/postprocess/texturize.lua:22"},
	{"RenderScreenspaceEffects", "Legs:Render", "addons/hex's server plugins/lua/hsp/gfx/cl_legs.lua:302"},
	{"RenderScreenspaceEffects", "RenderColorModify", "lua/postprocess/color_modify.lua:37"},
	{"RenderScreenspaceEffects", "RenderMotionBlur", "lua/postprocess/motion_blur.lua:66"},
	{"RenderScreenspaceEffects", "RenderMaterialOverlay", "lua/postprocess/overlay.lua:35"},
	{"RenderScreenspaceEffects", "RenderSobel", "lua/postprocess/sobel.lua:28"},
	{"RenderScreenspaceEffects", "RenderSharpen", "lua/postprocess/sharpen.lua:26"},
	{"RenderScreenspaceEffects", "DrawTWEffects", "addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:280"},
	{"RenderScreenspaceEffects", "RenderSunbeams", "lua/postprocess/sunbeams.lua:31"},
	{"UpdateAnimation", "Legs:UpdateAnimation", "addons/hex's server plugins/lua/hsp/gfx/cl_legs.lua:274"},
	{"GUIMouseReleased", "SpawnMenuOpenGUIMouseReleased", "gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:302"},
	{"GUIMouseReleased", "SuperDOFMouseUp", "lua/postprocess/super_dof.lua:376"},
	{"ScalePlayerDamage", "FixVehiclesDamagesPlayer", "addons/hex's server plugins/lua/hsp/deathmatch/sh_taucannon.lua:8"},
	{"AddToolMenuCategories", "CreateUtilitiesCategories", "lua/autorun/utilities_menu.lua:68"},
	{"OnEntityCreated", "ZLib_Installed", "addons/adv duplicator/lua/autorun/shared/dupeshare.lua:19"},
	{"OnSpawnMenuClose", "HSP.FixShift", "addons/hex's server plugins/lua/hsp/overrides/cl_shiftfix.lua:16"},
	{"OnSpawnMenuClose", "HSP.SpawnMenu_Close", "addons/hex's server plugins/lua/hsp/qmonitor/cl_qmonitor.lua:14"},
	{"SpawniconGenerated", "SpawniconGenerated", "lua/includes/gui/icon_progress.lua:7"},
	{"EntityRemoved", "DoDieFunction", "lua/includes/extensions/entity.lua:130"},
	{"VGUIMousePressAllowed", "WorldPickerMouseDisable", "lua/includes/extensions/util/worldpicker.lua:44"},
	{"PopulateWeapons", "AddWeaponContent", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/weapons.lua:2"},
	{"OnSaveSpawnlist", "DoSaveSpawnlist", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/custom.lua:196"},
	{"PhysgunPickup", "NoFIZZ", "addons/hex's server plugins/lua/hsp/antispam/sh_nofizz.lua:46"},
	{"LocalPlayerSpawn", "HSP.Sound_Stop", "addons/hex's server plugins/lua/hsp/general/cl_stopsounds.lua:18"},
	{"LocalPlayerSpawn", "HSP.FixAnim", "addons/hex's server plugins/lua/hsp/general/sh_fixswim.lua:16"},
	{"ScoreboardHide", "UH_ScoreBoard_Hide", "addons/uh scoreboard/lua/autorun/sh_scoreboard.lua:33"},
	{"HUDPaint", "PlayerOptionDraw", "lua/includes/extensions/client/player.lua:65"},
	{"HUDPaint", "DrawVoteWindow", "addons/hex's server plugins/lua/hsp/solidvote/cl_b_vote.lua:69"},
	{"HUDPaint", "OldNotify", "addons/hex's server plugins/lua/hsp/overrides/sh_ganfix.lua:142"},
	{"HUDPaint", "DrawRTTexture", "addons/re-located stools/lua/weapons/gmod_tool/stools/rtcamera.lua:183"},
	{"HUDPaint", "AltAmmoHUD", "addons/hex's server plugins/lua/hsp/gfx/cl_altammohud.lua:22"},
	{"HUDPaint", "SPropProtection.HUDPaint", "addons/spp/lua/spropprotection/cl_init.lua:33"},
	{"HUDPaint", "HACOldNotify", "addons/hex's anticheat/lua/hac/cl_message.lua:170"},
	{"HUDPaint", "HSP.Air_HUD", "addons/hex's server plugins/lua/hsp/airlevel/cl_airlevel.lua:10"},
	{"HUDPaint", "DrawRecordingIcon", "lua/autorun/client/gm_demo.lua:19"},
	{"HUDPaint", "CLScreenWaterOverlay", "addons/hex's server plugins/lua/hsp/gfx/cl_screenwater.lua:9"},
	{"HUDPaint", "AdvDupeProgressBar", "addons/adv duplicator/lua/autorun/client/cl_advdupe.lua:296"},
	{"HUDPaint", "HSP.RenderCenterMessage", "addons/hex's server plugins/lua/hsp/printmessage/cl_printmessage.lua:30"},
	{"HUDPaint", "MHud_Paint", "addons/hex's server plugins/lua/hsp/gfx/cl_hud.lua:42"},
	{"HUDShouldDraw", "MHud_Hide", "addons/hex's server plugins/lua/hsp/gfx/cl_hud.lua:16"},
	{"HUDPaint", "HSP.ShowHEV", "addons/hex's server plugins/lua/hsp/gfx/cl_hev.lua:75"},
	{"CreateMove", "ScreenLoggerKey", "addons/hex's server plugins/lua/hsp/gfx/cl_screenlogger.lua:21"},
	{"CreateMove", "SACM", "addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:371"},
	{"NeedsDepthPass", "NeedsDepthPass_Bokeh", "lua/postprocess/bokeh_dof.lua:39"},
	{"PostRender", "RenderFrameBlend", "lua/postprocess/frame_blend.lua:181"},
	{"PostRender", "RenderDupeIcon", "gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/icon.lua:3"},
	{"PreDrawHalos", "AddPhysgunHalos", "gamemodes/sandbox/gamemode/cl_init.lua:108"},
	{"Tick", "SendQueuedConsoleCommands", "lua/includes/extensions/player.lua:103"},
	{"Tick", "HSP.TimeGuard", "addons/hex's server plugins/lua/hsp/base/sh_b_oldtimer.lua:237"},
	{"Tick", "HSP.Air_ClientThink", "addons/hex's server plugins/lua/hsp/airlevel/cl_airlevel.lua:72"},
	{"PostGameSaved", "OnCreationsSaved", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/saves.lua:68"},
	{"SpawnlistOpenGenericMenu", "SpawnlistOpenGenericMenu", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentcontainer.lua:124"},
	{"PreventScreenClicks", "PreventScreenClicks", "addons/hex's server plugins/lua/hsp/overrides/cl_screenclicks.lua:8"},
	{"PreventScreenClicks", "PropertiesPreventClicks", "lua/includes/modules/properties.lua:179"},
	{"PreventScreenClicks", "HSP_PreventScreenClicks", "addons/hex's server plugins/lua/hsp/overrides/cl_screenclicks.lua:8"},
	{"PreventScreenClicks", "SuperDOFPreventClicks", "lua/postprocess/super_dof.lua:400"},
	{"PopulateVehicles", "AddEntityContent", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/vehicles.lua:2"},
	{"PlayerEndVoice", "PlayerEndVoice", "addons/hex's server plugins/lua/hsp/overrides/cl_newvoice.lua:28"},
	{"AfterPostEntity", "GPath_TX", "addons/hex's server plugins/lua/hsp/base/cl_b_gamepath.lua:10"},
	{"InitPostEntity", "ClassicTNT", "addons/hex's server plugins/lua/hsp/overrides/sh_classictnt.lua:8"},
	{"InitPostEntity", "HSP.UpdateWeaponTable", "addons/hex's server plugins/lua/hsp/base/sh_b_allweapons.lua:15"},
	{"InitPostEntity", "HSP.AfterPostEntity", "addons/hex's server plugins/lua/hsp/base/sh_b_afterpostentity.lua:8"},
	{"InitPostEntity", "CreateVoiceVGUI", "gamemodes/base/gamemode/cl_voice.lua:132"},
	{"InitPostEntity", "HSP.SetBaseProps", "addons/hex's server plugins/lua/hsp/antispam/sh_nofizz.lua:13"},
	{"InitPostEntity", "HSP.CSSCheck", "addons/hex's server plugins/lua/hsp/csscheck/cl_csscheck.lua:92"},
	{"OnSpawnMenuOpen", "HSP.FixShift", "addons/hex's server plugins/lua/hsp/overrides/cl_shiftfix.lua:17"},
	{"OnSpawnMenuOpen", "HSP.SpawnMenu_Open", "addons/hex's server plugins/lua/hsp/qmonitor/cl_qmonitor.lua:8"},
	{"PostPlayerDraw", "EndClip", "addons/hex's server plugins/lua/hsp/deathmatch/sh_spawneffect.lua:159"},
	{"SpawnMenuOpen", "SPropProtection.SpawnMenuOpen", "addons/spp/lua/spropprotection/cl_init.lua:132"},
	{"ChatText", "HSP.NoConnect", "addons/hex's server plugins/lua/hsp/connectmessage/cl_noconnect.lua:8"},
	{"RenderScene", "RenderSuperDoF", "lua/postprocess/super_dof.lua:323"},
	{"RenderScene", "RenderStereoscopy", "lua/postprocess/stereoscopy.lua:44"},
	{"DrawOverlay", "DragNDropPaint", "lua/includes/extensions/client/panel/dragdrop.lua:228"},
	{"DrawOverlay", "DrawNumberScratch", "lua/vgui/dnumberscratch.lua:343"},
	{"DrawOverlay", "VGUIShowLayoutPaint", "lua/includes/util/vgui_showlayout.lua:12"},
	{"GUIMousePressed", "SuperDOFMouseDown", "lua/postprocess/super_dof.lua:363"},
	{"GUIMousePressed", "SpawnMenuOpenGUIMousePressed", "gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:287"},
	{"GUIMousePressed", "PropertiesClick", "lua/includes/modules/properties.lua:167"},
	{"PreRender", "PreRenderFrameBlend", "lua/postprocess/frame_blend.lua:190"},
	{"Think", "RealFrameTime", "lua/includes/util/client.lua:11"},
	{"Think", "HSP.RSX_Think", "addons/hex's server plugins/lua/hsp/base/cl_b_prs.lua:24"},
	{"Think", "NotificationThink", "lua/includes/modules/notification.lua:135"},
	{"Think", "HSP.LocalPlayerSpawn", "addons/hex's server plugins/lua/hsp/base/cl_b_lps.lua:8"},
	{"Think", "CheckKeys", "addons/hex's anticheat/lua/hac/cl_takesc.lua:93"},
	{"Think", "CheckTimers2", "addons/hex's server plugins/lua/hsp/base/sh_b_oldtimer.lua:202"},
	{"Think", "SACH.CheckKeys", "addons/sach/lua/autorun/client/cl_sach.lua:1066"},
	{"Think", "KeyInput", "addons/hex's server plugins/lua/hsp/solidvote/cl_b_vote.lua:170"},
	{"Think", "CheckForDeadBro", "addons/hex's server plugins/lua/hsp/deathmatch/sh_spawneffect.lua:96"},
	{"Think", "DOFThink", "lua/postprocess/dof.lua:45"},
	{"Think", "RTDKey", "addons/hex's server plugins/lua/hsp/rtd/cl_rtd.lua:11"},
	{"OnSpawnMenuOpen", "RSX_OnSpawnMenuOpen", "addons/hex's server plugins/lua/hsp/base/cl_b_prs.lua:11"},
	{"OnContextMenuOpen", "RSX_OnContextMenuOpen", "addons/hex's server plugins/lua/hsp/base/cl_b_prs.lua:11"},
	{"ScoreboardShow", "RSX_ScoreboardShow", "addons/hex's server plugins/lua/hsp/base/cl_b_prs.lua:11"},
},


White_CCA = {
	{"pp_superdof", "lua/postprocess/super_dof.lua:320"},
	{"adv_duplicator_open_cl", "addons/adv duplicator/lua/weapons/gmod_tool/stools/adv_duplicator.lua:1412"},
	{"adv_duplicator_upload_cl", "addons/adv duplicator/lua/weapons/gmod_tool/stools/adv_duplicator.lua:1441"},
	{"adv_duplicator_open_cl2", "addons/adv duplicator/lua/weapons/gmod_tool/stools/adv_duplicator.lua:1426"},
	{"adv_duplicator_cl_menu", "addons/adv duplicator/lua/weapons/gmod_tool/stools/adv_duplicator.lua:1397"},
	{"hac_spectate_unload", "addons/hex's anticheat/lua/hac/tits.hac:711"},
	{"dupe_show", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenttypes/dupes.lua:107"},
	{"+menu", "gamemodes/base/gamemode/cl_spawnmenu.lua:66"},
	{"precision_setuser", "addons/phx/lua/weapons/gmod_tool/stools/precision.lua:1729"},
	{"stacker_resetoffsets", "addons/ol_stacker/lua/weapons/gmod_tool/stools/stacker.lua:289"},
	{"colmat_materiallist", "addons/adv duplicator/lua/weapons/gmod_tool/stools/colmat.lua:209"},
	{"-menu_context", "gamemodes/base/gamemode/cl_spawnmenu.lua:73"},
	{"+menu_context", "gamemodes/base/gamemode/cl_spawnmenu.lua:72"},
	{"fspectate", "addons/hex's anticheat/lua/hac/tits.hac:262"},
	{"togglefray", "addons/hex's anticheat/lua/hac/tits.hac:79"},
	{"gm_demo", "lua/autorun/client/gm_demo.lua:2"},
	{"adv_duplicator_confirmdelete_gui", "addons/adv duplicator/lua/autorun/client/cl_advdupe.lua:599"},
	{"lua_cookieclear", "lua/includes/modules/cookie.lua:120"},
	{"vote_yes", "addons/hex's server plugins/lua/hsp/solidvote/cl_b_vote.lua:157"},
	{"_hac_ready", "addons/hex's anticheat/lua/hac/cl_rsx.lua:35"},
	{"-ev_menu", "addons/fsamod/lua/fsa/client.lua:18"},
	{"adv_duplicator_makedir_gui", "addons/adv duplicator/lua/autorun/client/cl_advdupe.lua:458"},
	{"sach_reset", "addons/sach/lua/autorun/client/cl_sach.lua:1057"},
	{"sach", "addons/sach/lua/autorun/client/cl_sach.lua:1045"},
	{"rtcamera_window", "addons/re-located stools/lua/weapons/gmod_tool/stools/rtcamera.lua:143"},
	{"hsp_colors_cl", "addons/hex's server plugins/lua/hsp_shared.lua:68"},
	{"+ev_menu", "addons/fsamod/lua/fsa/client.lua:3"},
	{"precision_setmode", "addons/phx/lua/weapons/gmod_tool/stools/precision.lua:1720"},
	{"precision_generalmenu", "addons/phx/lua/weapons/gmod_tool/stools/precision.lua:1710"},
	{"precision_defaultrestore", "addons/phx/lua/weapons/gmod_tool/stools/precision.lua:1603"},
	{"dupe_arm", "gamemodes/sandbox/entities/weapons/gmod_tool/stools/duplicator/arming.lua:8"},
	{"adv_duplicator_cl_fileopts", "addons/adv duplicator/lua/autorun/client/cl_advdupe.lua:162"},
	{"hsp_maps", "addons/hex's server plugins/lua/hsp/solidvote/cl_v_map.lua:11"},
	{"lua_find_cl", "lua/autorun/developer_functions.lua:45"},
	{"-ass_menu", "addons/fsamod/lua/fsa/client.lua:18"},
	{"precision_updatecpanel", "addons/phx/lua/weapons/gmod_tool/stools/precision.lua:1738"},
	{"+ass_menu", "addons/fsamod/lua/fsa/client.lua:3"},
	{"adv_duplicator_renamefile_gui", "addons/adv duplicator/lua/autorun/client/cl_advdupe.lua:528"},
	{"derma_controls", "lua/derma/derma_example.lua:53"},
	{"-fsa_menu", "addons/fsamod/lua/fsa/client.lua:18"},
	{"-menu", "gamemodes/base/gamemode/cl_spawnmenu.lua:67"},
	{"vote_no", "addons/hex's server plugins/lua/hsp/solidvote/cl_b_vote.lua:162"},
	{"hac_streamhks", "addons/hex's anticheat/lua/en_streamhks.lua:291"},
	{"dupe_show", "addons/hex's server plugins/lua/hsp/overrides/sh_nodupe.lua:7"},
	{"dupe_arm", "addons/hex's server plugins/lua/hsp/overrides/sh_nodupe.lua:7"},
	{"dupe_publish", "addons/hex's server plugins/lua/hsp/overrides/sh_nodupe.lua:7"},
	{"adv_duplicator_save_gui", "addons/adv duplicator/lua/autorun/client/cl_advdupe.lua:398"},
	{"+fsa_menu", "addons/fsamod/lua/fsa/client.lua:3"},
	{"lua_cookiespew", "lua/includes/modules/cookie.lua:133"},
},


White_GM = {
	{"OnPlayerChatOld", "gamemodes/base/gamemode/cl_init.lua:140"},
	{"PreventScreenClicks", "gamemodes/base/gamemode/cl_init.lua:619"},
	{"AddNotify", "gamemodes/sandbox/gamemode/cl_notice.lua:2"},
	{"OnPlayerChat", "gamemodes/base/gamemode/player_shd.lua:109"},
	{"HUDWeaponPickedUp", "gamemodes/base/gamemode/cl_hudpickup.lua:11"},
	{"CalcViewModelView", "gamemodes/base/gamemode/cl_init.lua:541"},
	{"SpawnMenuOpen", "gamemodes/sandbox/gamemode/cl_spawnmenu.lua:19"},
	{"PopulateSTOOLMenu", "gamemodes/base/gamemode/cl_spawnmenu.lua:38"},
	{"ChatText", "gamemodes/base/gamemode/cl_init.lua:212"},
	{"GetGameDescription", "gamemodes/base/gamemode/shared.lua:108"},
	{"Restored", "gamemodes/base/gamemode/shared.lua:123"},
	{"OnEntityCreated", "gamemodes/base/gamemode/shared.lua:148"},
	{"DrawDeathNotice", "gamemodes/base/gamemode/cl_deathnotice.lua:193"},
	{"PostDrawHUD", "gamemodes/base/gamemode/cl_init.lua:651"},
	{"RenderScene", "gamemodes/base/gamemode/cl_init.lua:273"},
	{"DoModelSearch", "gamemodes/sandbox/gamemode/cl_spawnmenu.lua:168"},
	{"PlayerStepSoundTime", "gamemodes/base/gamemode/player_shd.lua:70"},
	{"Think", "gamemodes/base/gamemode/cl_init.lua:33"},
	{"AddSTOOL", "gamemodes/sandbox/gamemode/cl_spawnmenu.lua:51"},
	{"DrawOverlay", "gamemodes/base/gamemode/cl_init.lua:655"},
	{"GUIMousePressed", "gamemodes/base/gamemode/cl_init.lua:635"},
	{"HUDPaintBackground", "gamemodes/base/gamemode/cl_init.lua:94"},
	{"CanConstruct", "gamemodes/sandbox/gamemode/shared.lua:74"},
	{"TranslateActivity", "gamemodes/base/gamemode/animations.lua:317"},
	{"CloseDermaMenus", "gamemodes/base/gamemode/cl_init.lua:675"},
	{"CanConstrain", "gamemodes/sandbox/gamemode/shared.lua:52"},
	{"PlayerConnect", "gamemodes/base/gamemode/shared.lua:56"},
	{"Move", "gamemodes/base/gamemode/shared.lua:203"},
	{"DoAnimationEvent", "gamemodes/base/gamemode/animations.lua:343"},
	{"SpawnMenuEnabled", "gamemodes/sandbox/gamemode/cl_spawnmenu.lua:10"},
	{"SetupMove", "gamemodes/base/gamemode/shared.lua:215"},
	{"InputMouseApply", "gamemodes/base/gamemode/cl_init.lua:455"},
	{"CanDrive", "gamemodes/sandbox/gamemode/shared.lua:327"},
	{"ShouldDrawLocalPlayer", "gamemodes/base/gamemode/cl_init.lua:382"},
	{"GetTeamNumColor", "gamemodes/base/gamemode/cl_init.lua:140"},
	{"PlayerAuthed", "gamemodes/base/gamemode/shared.lua:64"},
	{"HandlePlayerJumping", "gamemodes/base/gamemode/animations.lua:1"},
	{"AddHint", "gamemodes/sandbox/gamemode/cl_hints.lua:28"},
	{"Initialize", "gamemodes/sandbox/gamemode/cl_init.lua:26"},
	{"ShowTeam", "gamemodes/base/gamemode/cl_pickteam.lua:6"},
	{"OnContextMenuClose", "gamemodes/sandbox/gamemode/spawnmenu/contextmenu.lua:249"},
	{"UnfrozeObjects", "gamemodes/sandbox/gamemode/cl_init.lua:61"},
	{"HandlePlayerLanding", "gamemodes/base/gamemode/animations.lua:121"},
	{"GetVehicles", "gamemodes/base/gamemode/cl_init.lua:263"},
	{"HandlePlayerVaulting", "gamemodes/base/gamemode/animations.lua:93"},
	{"HUDWeaponPickedUp", "addons/hex's server plugins/lua/hsp/overrides/cl_pickupfix.lua:8"},
	{"OnAchievementAchieved", "gamemodes/base/gamemode/cl_init.lua:467"},
	{"CanProperty", "gamemodes/sandbox/gamemode/shared.lua:277"},
	{"PopulatePropMenu", "gamemodes/sandbox/gamemode/cl_spawnmenu.lua:102"},
	{"SetPlayerSpeed", "gamemodes/base/gamemode/player_shd.lua:17"},
	{"HUDDrawTargetID", "gamemodes/base/gamemode/cl_targetid.lua:7"},
	{"RenderScreenspaceEffects", "gamemodes/base/gamemode/cl_init.lua:119"},
	{"OnUndo", "gamemodes/sandbox/gamemode/cl_init.lua:39"},
	{"OnEntityCreated", "gamemodes/base/gamemode/shared.lua:139"},
	{"CalcViewModelView", "gamemodes/base/gamemode/cl_init.lua:556"},
	{"AdjustMouseSensitivity", "gamemodes/base/gamemode/cl_init.lua:409"},
	{"Saved", "gamemodes/base/gamemode/shared.lua:107"},
	{"PhysgunPickup", "gamemodes/sandbox/gamemode/shared.lua:115"},
	{"GUIMouseReleased", "gamemodes/base/gamemode/cl_init.lua:681"},
	{"FinishChat", "gamemodes/base/gamemode/cl_init.lua:227"},
	{"PreDrawHUD", "gamemodes/base/gamemode/cl_init.lua:685"},
	{"PreGamemodeLoaded", "gamemodes/base/gamemode/shared.lua:289"},
	{"HUDShouldDraw", "gamemodes/base/gamemode/cl_init.lua:49"},
	{"PlayerPostThink", "gamemodes/base/gamemode/shared.lua:252"},
	{"UpdateAnimation", "gamemodes/base/gamemode/animations.lua:167"},
	{"PlayerDriveAnimate", "gamemodes/sandbox/gamemode/shared.lua:285"},
	{"PlayerSwitchWeapon", "gamemodes/base/gamemode/player_shd.lua:142"},
	{"Tick", "gamemodes/base/gamemode/shared.lua:132"},
	{"PreDrawTranslucentRenderables", "gamemodes/base/gamemode/cl_init.lua:538"},
	{"PreventScreenClicks", "gamemodes/base/gamemode/cl_init.lua:657"},
	{"PostDrawViewModel", "gamemodes/base/gamemode/cl_init.lua:601"},
	{"ShouldCollide", "gamemodes/base/gamemode/shared.lua:183"},
	{"PreDrawViewModel", "gamemodes/base/gamemode/cl_init.lua:586"},
	{"PlayerShouldTakeDamage", "gamemodes/base/gamemode/shared.lua:92"},
	{"PreDrawEffects", "gamemodes/base/gamemode/cl_init.lua:701"},
	{"PhysgunDrop", "gamemodes/base/gamemode/shared.lua:85"},
	{"PreRender", "gamemodes/base/gamemode/cl_init.lua:276"},
	{"PlayerBindPress", "gamemodes/base/gamemode/cl_init.lua:39"},
	{"PrePlayerDraw", "gamemodes/base/gamemode/cl_init.lua:448"},
	{"HandlePlayerSwimming", "gamemodes/base/gamemode/animations.lua:104"},
	{"PostDrawTranslucentRenderables", "gamemodes/base/gamemode/cl_init.lua:548"},
	{"ChatTextChanged", "gamemodes/base/gamemode/cl_init.lua:233"},
	{"HandlePlayerDriving", "gamemodes/base/gamemode/animations.lua:128"},
	{"DrawMonitors", "gamemodes/base/gamemode/cl_init.lua:697"},
	{"EntityKeyValue", "gamemodes/sandbox/gamemode/shared.lua:166"},
	{"PostGamemodeLoaded", "gamemodes/base/gamemode/shared.lua:296"},
	{"HandlePlayerDucking", "gamemodes/base/gamemode/animations.lua:52"},
	{"CreateTeams", "gamemodes/base/gamemode/shared.lua:154"},
	{"OnGamemodeLoaded", "gamemodes/base/gamemode/shared.lua:293"},
	{"CalcMainActivity", "gamemodes/base/gamemode/animations.lua:269"},
	{"EntityRemoved", "gamemodes/base/gamemode/shared.lua:124"},
	{"FinishMove", "gamemodes/base/gamemode/shared.lua:216"},
	{"FindUseEntity", "gamemodes/base/gamemode/player_shd.lua:122"},
	{"OnPlayerChat", "gamemodes/base/gamemode/cl_init.lua:140"},
	{"OnChatTab", "gamemodes/base/gamemode/cl_init.lua:179"},
	{"PostDrawSkyBox", "gamemodes/base/gamemode/cl_init.lua:502"},
	{"CanTool", "gamemodes/sandbox/gamemode/shared.lua:51"},
	{"PostDrawOpaqueRenderables", "gamemodes/base/gamemode/cl_init.lua:530"},
	{"CreateMove", "gamemodes/base/gamemode/cl_init.lua:645"},
	{"ForceDermaSkin", "gamemodes/base/gamemode/cl_init.lua:428"},
	{"PreDrawOpaqueRenderables", "gamemodes/base/gamemode/cl_init.lua:520"},
	{"OnViewModelChanged", "gamemodes/base/gamemode/shared.lua:308"},
	{"CalcVehicleView", "gamemodes/base/gamemode/cl_init.lua:298"},
	{"PreDrawHalos", "gamemodes/base/gamemode/cl_init.lua:709"},
	{"PostRender", "gamemodes/base/gamemode/cl_init.lua:284"},
	{"PostDraw2DSkyBox", "gamemodes/base/gamemode/cl_init.lua:512"},
	{"PostProcessPermitted", "gamemodes/base/gamemode/cl_init.lua:257"},
	{"AddDeathNotice", "gamemodes/base/gamemode/cl_deathnotice.lua:139"},
	{"GUIMouseDoublePressed", "gamemodes/base/gamemode/cl_init.lua:91"},
	{"CalcView", "gamemodes/base/gamemode/cl_init.lua:784"},
	{"HandlePlayerNoClipping", "gamemodes/base/gamemode/animations.lua:66"},
	{"ShutDown", "gamemodes/base/gamemode/cl_init.lua:101"},
	{"MouthMoveAnimation", "gamemodes/base/gamemode/animations.lua:247"},
	{"PreDrawSkyBox", "gamemodes/base/gamemode/cl_init.lua:492"},
	{"VehicleMove", "gamemodes/base/gamemode/shared.lua:226"},
	{"InitPostEntity", "gamemodes/base/gamemode/cl_init.lua:24"},
	{"PostPlayerDraw", "gamemodes/base/gamemode/cl_init.lua:439"},
	{"PlayerTick", "gamemodes/base/gamemode/player_shd.lua:135"},
	{"ChatText", "gamemodes/base/gamemode/cl_init.lua:241"},
	{"RenderScene", "gamemodes/base/gamemode/cl_init.lua:292"},
	{"CreateClientsideRagdoll", "gamemodes/base/gamemode/cl_init.lua:717"},
	{"HUDPaintBackground", "gamemodes/base/gamemode/cl_init.lua:84"},
	{"PostDrawHUD", "gamemodes/base/gamemode/cl_init.lua:689"},
	{"DoAnimationEvent", "gamemodes/base/gamemode/animations.lua:326"},
	{"GravGunPunt", "gamemodes/sandbox/gamemode/shared.lua:86"},
	{"DrawOverlay", "gamemodes/base/gamemode/cl_init.lua:693"},
	{"GUIMousePressed", "gamemodes/base/gamemode/cl_init.lua:673"},
	{"TranslateActivity", "gamemodes/base/gamemode/animations.lua:313"},
	{"PropBreak", "gamemodes/base/gamemode/shared.lua:64"},
	{"Restored", "gamemodes/base/gamemode/shared.lua:114"},
	{"CloseDermaMenus", "gamemodes/base/gamemode/cl_init.lua:713"},
	{"DrawDeathNotice", "gamemodes/base/gamemode/cl_deathnotice.lua:192"},
	{"Think", "gamemodes/base/gamemode/cl_init.lua:32"},
	{"GetGameDescription", "gamemodes/base/gamemode/shared.lua:99"},
	{"SetupMove", "gamemodes/base/gamemode/shared.lua:206"},
	{"InputMouseApply", "gamemodes/base/gamemode/cl_init.lua:470"},
	{"CanDrive", "gamemodes/sandbox/gamemode/shared.lua:251"},
	{"ShouldDrawLocalPlayer", "gamemodes/base/gamemode/cl_init.lua:397"},
	{"GetTeamNumColor", "gamemodes/base/gamemode/cl_init.lua:130"},
	{"HandlePlayerJumping", "gamemodes/base/gamemode/animations.lua:2"},
	{"GetTeamColor", "gamemodes/base/gamemode/cl_init.lua:117"},
	{"HandlePlayerLanding", "gamemodes/base/gamemode/animations.lua:118"},
	{"OnReloaded", "gamemodes/base/gamemode/shared.lua:285"},
	{"EndEntityDriving", "gamemodes/base/gamemode/shared.lua:268"},
	{"OnAchievementAchieved", "gamemodes/base/gamemode/cl_init.lua:482"},
	{"CanProperty", "gamemodes/sandbox/gamemode/shared.lua:201"},
	{"RenderScreenspaceEffects", "gamemodes/base/gamemode/cl_init.lua:109"},
	{"StartEntityDriving", "gamemodes/base/gamemode/shared.lua:259"},
	{"GravGunPickupAllowed", "gamemodes/sandbox/gamemode/shared.lua:100"},
	{"GetMotionBlurValues", "gamemodes/base/gamemode/cl_init.lua:457"},
	{"GrabEarAnimation", "gamemodes/base/gamemode/animations.lua:222"},
	{"PlayerNoClip", "gamemodes/sandbox/gamemode/shared.lua:185"},
	{"PostDrawEffects", "gamemodes/base/gamemode/cl_init.lua:705"},
	{"Move", "gamemodes/base/gamemode/shared.lua:194"},
	{"StartChat", "gamemodes/base/gamemode/cl_init.lua:220"},
	{"GetMotionBlurValues", "gamemodes/base/gamemode/cl_init.lua:442"},
	{"PostDraw2DSkyBox", "gamemodes/base/gamemode/cl_init.lua:497"},
	{"ContextMenuOpen", "gamemodes/sandbox/gamemode/cl_spawnmenu.lua:31"},
	{"CanPlayerUnfreeze", "gamemodes/sandbox/gamemode/shared.lua:228"},
	{"PostProcessPermitted", "gamemodes/base/gamemode/cl_init.lua:228"},
	{"PlayerDeath", "gamemodes/base/gamemode/cl_init.lua:42"},
	{"UpdateAnimation", "gamemodes/base/gamemode/animations.lua:170"},
	{"CanPose", "gamemodes/sandbox/gamemode/shared.lua:99"},
	{"StartChat", "gamemodes/base/gamemode/cl_init.lua:191"},
	{"AddToolMenuCategories", "gamemodes/sandbox/gamemode/cl_spawnmenu.lua:93"},
	{"PlayerEnteredVehicle", "gamemodes/base/gamemode/player_shd.lua:38"},
	{"AddGamemodeToolMenuTabs", "gamemodes/sandbox/gamemode/cl_spawnmenu.lua:60"},
	{"GetTeamColor", "gamemodes/base/gamemode/cl_init.lua:127"},
	{"AdjustMouseSensitivity", "gamemodes/base/gamemode/cl_init.lua:394"},
	{"Saved", "gamemodes/base/gamemode/shared.lua:116"},
	{"PlayerStartVoice", "gamemodes/base/gamemode/cl_voice.lua:72"},
	{"KeyRelease", "gamemodes/base/gamemode/shared.lua:48"},
	{"PhysgunPickup", "gamemodes/sandbox/gamemode/shared.lua:179"},
	{"GUIMouseReleased", "gamemodes/base/gamemode/cl_init.lua:643"},
	{"FinishChat", "gamemodes/base/gamemode/cl_init.lua:198"},
	{"PreDrawHUD", "gamemodes/base/gamemode/cl_init.lua:647"},
	{"PreGamemodeLoaded", "gamemodes/base/gamemode/shared.lua:298"},
	{"HUDPaint", "gamemodes/sandbox/gamemode/cl_init.lua:70"},
	{"PlayerPostThink", "gamemodes/base/gamemode/shared.lua:261"},
	{"PostDrawEffects", "gamemodes/base/gamemode/cl_init.lua:667"},
	{"HideTeam", "gamemodes/base/gamemode/cl_pickteam.lua:58"},
	{"PlayerDriveAnimate", "gamemodes/sandbox/gamemode/shared.lua:361"},
	{"PlayerSwitchWeapon", "gamemodes/base/gamemode/player_shd.lua:182"},
	{"LimitHit", "gamemodes/sandbox/gamemode/cl_init.lua:32"},
	{"Tick", "gamemodes/base/gamemode/shared.lua:141"},
	{"PreDrawTranslucentRenderables", "gamemodes/base/gamemode/cl_init.lua:523"},
	{"PreventScreenClicks", "addons/hex's server plugins/lua/hsp/overrides/cl_screenclicks.lua:8"},
	{"AddNotify", "addons/hex's server plugins/lua/hsp/overrides/sh_ganfix.lua:52"},
	{"OnCleanup", "gamemodes/sandbox/gamemode/cl_init.lua:52"},
	{"HUDWeaponPickedUpOld", "gamemodes/base/gamemode/cl_hudpickup.lua:11"},
	{"PostDrawViewModel", "gamemodes/base/gamemode/cl_init.lua:572"},
	{"ShouldCollide", "gamemodes/base/gamemode/shared.lua:192"},
	{"PaintNotes", "gamemodes/sandbox/gamemode/cl_notice.lua:8"},
	{"GrabEarAnimation", "gamemodes/base/gamemode/animations.lua:225"},
	{"NetworkEntityCreated", "gamemodes/sandbox/gamemode/cl_init.lua:133"},
	{"PlayerShouldTakeDamage", "gamemodes/base/gamemode/shared.lua:101"},
	{"OnSpawnMenuOpen", "gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:222"},
	{"PaintWorldTips", "gamemodes/sandbox/gamemode/cl_worldtips.lua:85"},
	{"PreDrawEffects", "gamemodes/base/gamemode/cl_init.lua:663"},
	{"GravGunPickupAllowed", "gamemodes/sandbox/gamemode/shared.lua:164"},
	{"PlayerFootstep", "gamemodes/base/gamemode/player_shd.lua:49"},
	{"KeyPress", "gamemodes/base/gamemode/shared.lua:40"},
	{"PreRender", "gamemodes/base/gamemode/cl_init.lua:247"},
	{"PlayerBindPress", "gamemodes/base/gamemode/cl_init.lua:49"},
	{"HUDDrawPickupHistory", "gamemodes/base/gamemode/cl_hudpickup.lua:128"},
	{"PrePlayerDraw", "gamemodes/base/gamemode/cl_init.lua:433"},
	{"HandlePlayerSwimming", "gamemodes/base/gamemode/animations.lua:103"},
	{"PostReloadToolsMenu", "gamemodes/base/gamemode/cl_spawnmenu.lua:53"},
	{"PostDrawTranslucentRenderables", "gamemodes/base/gamemode/cl_init.lua:533"},
	{"ChatTextChanged", "gamemodes/base/gamemode/cl_init.lua:204"},
	{"HandlePlayerDriving", "gamemodes/base/gamemode/animations.lua:131"},
	{"DrawMonitors", "gamemodes/base/gamemode/cl_init.lua:659"},
	{"EntityKeyValue", "gamemodes/sandbox/gamemode/shared.lua:241"},
	{"EndEntityDriving", "gamemodes/base/gamemode/shared.lua:277"},
	{"PostGamemodeLoaded", "gamemodes/base/gamemode/shared.lua:305"},
	{"GetSpawnmenuTools", "gamemodes/sandbox/gamemode/cl_spawnmenu.lua:43"},
	{"HandlePlayerDucking", "gamemodes/base/gamemode/animations.lua:51"},
	{"PlayerTraceAttack", "gamemodes/base/gamemode/player_shd.lua:7"},
	{"CreateTeams", "gamemodes/base/gamemode/shared.lua:163"},
	{"OnGamemodeLoaded", "gamemodes/base/gamemode/shared.lua:302"},
	{"MouthMoveAnimation", "gamemodes/base/gamemode/animations.lua:250"},
	{"CPPIFriendsChanged", "addons/spp/lua/spropprotection/sh_cppi.lua:147"},
	{"CPPIAssignOwnership", "addons/spp/lua/spropprotection/sh_cppi.lua:145"},
	{"PostRenderVGUI", "gamemodes/sandbox/gamemode/cl_init.lua:84"},
	{"OnSpawnMenuClose", "gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:236"},
	{"CalcMainActivity", "gamemodes/base/gamemode/animations.lua:272"},
	{"PostDrawSkyBox", "gamemodes/base/gamemode/cl_init.lua:487"},
	{"HUDAmmoPickedUp", "gamemodes/base/gamemode/cl_hudpickup.lua:75"},
	{"EntityRemoved", "gamemodes/base/gamemode/shared.lua:133"},
	{"FinishMove", "gamemodes/base/gamemode/shared.lua:225"},
	{"FindUseEntity", "gamemodes/base/gamemode/player_shd.lua:162"},
	{"OnPlayerChat", "addons/hex's server plugins/lua/hsp/overrides/cl_chatnamefix.lua:12"},
	{"ForceDermaSkin", "gamemodes/base/gamemode/cl_init.lua:413"},
	{"AddGamemodeToolMenuCategories", "gamemodes/sandbox/gamemode/cl_spawnmenu.lua:80"},
	{"ScoreboardHide", "gamemodes/base/gamemode/cl_scoreboard.lua:263"},
	{"CalcVehicleView", "gamemodes/base/gamemode/cl_init.lua:279"},
	{"VehicleMove", "gamemodes/base/gamemode/shared.lua:235"},
	{"PostRender", "gamemodes/base/gamemode/cl_init.lua:255"},
	{"SuppressHint", "gamemodes/sandbox/gamemode/cl_hints.lua:40"},
	{"PopulateToolMenu", "gamemodes/base/gamemode/cl_spawnmenu.lua:59"},
	{"PreReloadToolsMenu", "gamemodes/base/gamemode/cl_spawnmenu.lua:45"},
	{"OnChatTab", "gamemodes/base/gamemode/cl_init.lua:150"},
	{"DrawPhysgunBeam", "gamemodes/sandbox/gamemode/cl_init.lua:96"},
	{"CanTool", "gamemodes/sandbox/gamemode/shared.lua:115"},
	{"PostDrawOpaqueRenderables", "gamemodes/base/gamemode/cl_init.lua:515"},
	{"CanRender", "gamemodes/sandbox/gamemode/shared.lua:107"},
	{"HUDShouldDraw", "gamemodes/base/gamemode/cl_init.lua:59"},
	{"PreDrawOpaqueRenderables", "gamemodes/base/gamemode/cl_init.lua:505"},
	{"PlayerHurt", "gamemodes/base/gamemode/shared.lua:32"},
	{"OnViewModelChanged", "gamemodes/base/gamemode/shared.lua:317"},
	{"GUIMouseDoublePressed", "gamemodes/base/gamemode/cl_init.lua:101"},
	{"CanPlayerEnterVehicle", "gamemodes/base/gamemode/player_shd.lua:30"},
	{"PreDrawHalos", "gamemodes/base/gamemode/cl_init.lua:671"},
	{"CalcView", "gamemodes/base/gamemode/cl_init.lua:688"},
	{"PropBreak", "gamemodes/base/gamemode/shared.lua:73"},
	{"OnReloaded", "gamemodes/base/gamemode/shared.lua:294"},
	{"StartEntityDriving", "gamemodes/base/gamemode/shared.lua:268"},
	{"AddDeathNotice", "gamemodes/base/gamemode/cl_deathnotice.lua:140"},
	{"OnContextMenuOpen", "gamemodes/sandbox/gamemode/spawnmenu/contextmenu.lua:236"},
	{"HandlePlayerNoClipping", "gamemodes/base/gamemode/animations.lua:65"},
	{"PhysgunDrop", "gamemodes/base/gamemode/shared.lua:94"},
	{"PreDrawSkyBox", "gamemodes/base/gamemode/cl_init.lua:477"},
	{"AddToolMenuTabs", "gamemodes/sandbox/gamemode/cl_spawnmenu.lua:71"},
	{"HUDDrawScoreBoard", "gamemodes/base/gamemode/cl_scoreboard.lua:276"},
	{"GravGunPunt", "gamemodes/sandbox/gamemode/shared.lua:150"},
	{"PlayerEndVoice", "gamemodes/base/gamemode/cl_voice.lua:118"},
	{"ShutDown", "gamemodes/base/gamemode/cl_init.lua:111"},
	{"PlayerNoClip", "gamemodes/sandbox/gamemode/shared.lua:261"},
	{"ScoreboardShow", "gamemodes/base/gamemode/cl_scoreboard.lua:245"},
	{"PlayerTick", "gamemodes/base/gamemode/player_shd.lua:175"},
	{"CreateMove", "gamemodes/base/gamemode/cl_init.lua:607"},
	{"InitPostEntity", "gamemodes/base/gamemode/cl_init.lua:25"},
	{"HUDItemPickedUp", "gamemodes/base/gamemode/cl_hudpickup.lua:44"},
	{"PreDrawViewModel", "gamemodes/base/gamemode/cl_init.lua:557"},
	{"PostPlayerDraw", "gamemodes/base/gamemode/cl_init.lua:424"},
	{"CreateClientsideRagdoll", "gamemodes/base/gamemode/cl_init.lua:679"},
},


White_Font = {

	{"CountDown", "addons/hex's server plugins/lua/hsp/general/cl_scountdown.lua:3"},
	{"GModToolName", "gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:21"},
	{"GModToolSubtitle", "gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:28"},
	{"GModToolHelp", "gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:35"},
	{"MHud_20", "addons/hex's server plugins/lua/hsp/gfx/cl_hud.lua:8"},
	{"BebasNeue", "addons/hex's server plugins/lua/hsp/killfeed/cl_dmsg.lua:3"},
	{"BebasNeue2", "addons/hex's server plugins/lua/hsp/killfeed/cl_dmsg.lua:12"},
	{"BebasNeue3", "addons/hex's server plugins/lua/hsp/killfeed/cl_dmsg.lua:21"},
	{"FS_EFont", "addons/hex's anticheat/lua/hac/tits.hac:191"},
	{"FS_Font", "addons/hex's anticheat/lua/hac/tits.hac:200"},
	{"Cluckshot", "addons/guided chicken/lua/weapons/weapon_chicken/cl_init.lua:46"},
	{"DermaDefault", "lua/derma/init.lua:15"},
	{"DermaDefaultBold", "lua/derma/init.lua:23"},
	{"DermaDefault", "lua/derma/init.lua:34"},
	{"DermaDefaultBold", "lua/derma/init.lua:42"},
	{"DermaLarge", "lua/derma/init.lua:52"},
	{"GModNotify", "lua/includes/modules/notification.lua:1"},
	{"ScoreboardDefault", "gamemodes/base/gamemode/cl_scoreboard.lua:2"},
	{"ScoreboardDefaultTitle", "gamemodes/base/gamemode/cl_scoreboard.lua:9"},
	{"FRETTA_HUGE", "addons/hex's server plugins/lua/hsp/base/cl_b_enum.lua:8"},
	{"FRETTA_HUGE_SHADOW", "addons/hex's server plugins/lua/hsp/base/cl_b_enum.lua:17"},
	{"FRETTA_LARGE", "addons/hex's server plugins/lua/hsp/base/cl_b_enum.lua:27"},
	{"FRETTA_LARGE_SHADOW", "addons/hex's server plugins/lua/hsp/base/cl_b_enum.lua:36"},
	{"FRETTA_MEDIUM", "addons/hex's server plugins/lua/hsp/base/cl_b_enum.lua:46"},
	{"FRETTA_MEDIUM_SHADOW", "addons/hex's server plugins/lua/hsp/base/cl_b_enum.lua:55"},
	{"FRETTA_SMALL", "addons/hex's server plugins/lua/hsp/base/cl_b_enum.lua:65"},
	{"FRETTA_NOTIFY", "addons/hex's server plugins/lua/hsp/base/cl_b_enum.lua:74"},
	{"Trebuchet22", "addons/hex's server plugins/lua/hsp/csscheck/cl_csscheck.lua:8"},
	{"Trebuchet20", "addons/hex's server plugins/lua/hsp/csscheck/cl_csscheck.lua:18"},
	{"Trebuchet19", "addons/hex's server plugins/lua/hsp/csscheck/cl_csscheck.lua:27"},
	{"AltAmmoHUD", "addons/hex's server plugins/lua/hsp/gfx/cl_altammohud.lua:7"},
	{"CV20", "addons/hex's server plugins/lua/hsp/gfx/cl_nametags.lua:11"},
	{"CV10", "addons/hex's server plugins/lua/hsp/gfx/cl_nametags.lua:21"},
	{"TabLarge", "addons/hex's server plugins/lua/hsp/gfx/cl_screenlogger.lua:8"},
	{"DamFont", "addons/hex's server plugins/lua/hsp/hitpoints/cl_hitpoints.lua:46"},
	{"GModNotify2", "addons/hex's server plugins/lua/hsp/overrides/sh_ganfix.lua:30"},
	{"GMDM_DPM_Center", "addons/hex's server plugins/lua/hsp/printmessage/cl_printmessage.lua:10"},
	{"Title", "addons/hex's server plugins/lua/hsp/solidvote/cl_b_vote.lua:24"},
	{"Result", "addons/hex's server plugins/lua/hsp/solidvote/cl_b_vote.lua:33"},
	{"Question", "addons/hex's server plugins/lua/hsp/solidvote/cl_b_vote.lua:42"},
	{"ResultMsg", "addons/hex's server plugins/lua/hsp/solidvote/cl_b_vote.lua:51"},
	{"ScoreboardPlayerName", "addons/uh scoreboard/lua/uh_scoreboard/player_row.lua:4"},
	{"ScoreboardPlayerNameBig", "addons/uh scoreboard/lua/uh_scoreboard/player_row.lua:5"},
	{"ScoreboardHeader", "addons/uh scoreboard/lua/uh_scoreboard/scoreboard.lua:5"},
	{"ScoreboardSubtitle", "addons/uh scoreboard/lua/uh_scoreboard/scoreboard.lua:6"},
	{"DefaultSmall2", "addons/uh scoreboard/lua/uh_scoreboard/scoreboard.lua:7"},
	{"Default", "addons/spp/lua/spropprotection/cl_init.lua:22"},
	{"Default12B", "addons/sach/lua/autorun/client/cl_sach.lua:17"},
	{"Default13B", "addons/sach/lua/autorun/client/cl_sach.lua:26"},
	{"Default14BA", "addons/sach/lua/autorun/client/cl_sach.lua:35"},
	{"GModNotify2", "addons/hex's anticheat/lua/hac/cl_message.lua:81"},
	{"HL2KillIcons", "addons/twitch weaponry/lua/autorun/client/spawnmenu_menu.lua:4"},
	{"HL2SelectIcons", "addons/twitch weaponry/lua/autorun/client/spawnmenu_menu.lua:13"},
	{"TargetID", "addons/fsamod/lua/vgui/fsamainmenu.lua:3"},
	{"TargetIDSmall", "addons/fsamod/lua/vgui/fsamainmenu.lua:13"},
	{"ContentHeader", "gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contentheader.lua:3"},
	{"GModWorldtip", "gamemodes/sandbox/gamemode/cl_worldtips.lua:3"},
	{"CSKillIcons", "addons/cs guns/lua/weapons/cse_base/shared.lua:19"},
	{"CSSelectIcons", "addons/cs guns/lua/weapons/cse_base/shared.lua:27"},
	{"CSKillIcons", "addons/cs guns/lua/weapons/cse_base_s/shared.lua:16"},
	{"CSSelectIcons", "addons/cs guns/lua/weapons/cse_base_s/shared.lua:24"},
	{"GModToolScreen", "gamemodes/sandbox/entities/weapons/gmod_tool/cl_viewscreen.lua:13"},
	{"CSKillIcons", "addons/counter-strike gm13/lua/weapons/weapon_cs_base/shared.lua:21"},
	{"CSSelectIcons", "addons/counter-strike gm13/lua/weapons/weapon_cs_base/shared.lua:29"},
	{"hl2c_crosshair1", "addons/ion cannon/lua/weapons/weapon_ioncannon/shared.lua:326"},
	{"CSKillIcons", "addons/toybox ports/lua/weapons/weapon_knife/shared.lua:15"},
	{"CSSelectIcons", "addons/toybox ports/lua/weapons/weapon_knife/shared.lua:23"},
	{"TargetIDSmall", "addons/mad c4/lua/weapons/weapon_mad_base/cl_init.lua:5"},
	{"HL2MP", "addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:463"},
	{"HL2MP", "addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:454"},
	{"HL2MP", "addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:460"},
	{"HL2MP", "addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:456"},
	{"DefaultC4", "addons/mad c4/lua/entities/ent_mad_c4/cl_init.lua:5"},
	{"HostFont", "addons/3d scoreboard/lua/entities/uh_scoreboard/cl_init.lua:5"},
	{"PlayerFont", "addons/3d scoreboard/lua/entities/uh_scoreboard/cl_init.lua:14"},
	{"UH_BB_MISSILE", "addons/love missile/lua/entities/uh_bb_missile/cl_init.lua:23"},
},


White_CCC = {
	["CreateClientConVar(pp_bloom,0,true,false) [lua/postprocess/bloom.lua:15]"] = 1,
	["CreateClientConVar(pp_bloom_darken,0.65,true,false) [lua/postprocess/bloom.lua:16]"] = 1,
	["CreateClientConVar(pp_bloom_multiply,1.0,true,false) [lua/postprocess/bloom.lua:17]"] = 1,
	["CreateClientConVar(pp_bloom_sizex,4.0,true,false) [lua/postprocess/bloom.lua:18]"] = 1,
	["CreateClientConVar(pp_bloom_sizey,4.0,true,false) [lua/postprocess/bloom.lua:19]"] = 1,
	["CreateClientConVar(pp_bloom_color,2.0,true,false) [lua/postprocess/bloom.lua:20]"] = 1,
	["CreateClientConVar(pp_bloom_color_r,255,true,false) [lua/postprocess/bloom.lua:21]"] = 1,
	["CreateClientConVar(pp_bloom_color_g,255,true,false) [lua/postprocess/bloom.lua:22]"] = 1,
	["CreateClientConVar(pp_bloom_color_b,255,true,false) [lua/postprocess/bloom.lua:23]"] = 1,
	["CreateClientConVar(pp_bloom_passes,4,true,false) [lua/postprocess/bloom.lua:24]"] = 1,
	["CreateClientConVar(pp_bokeh_blur,5,true,false) [lua/postprocess/bokeh_dof.lua:4]"] = 1,
	["CreateClientConVar(pp_bokeh_distance,0.1,true,false) [lua/postprocess/bokeh_dof.lua:5]"] = 1,
	["CreateClientConVar(pp_bokeh_focus,1.0,true,false) [lua/postprocess/bokeh_dof.lua:6]"] = 1,
	["CreateClientConVar(pp_bokeh,0,true,false) [lua/postprocess/bokeh_dof.lua:7]"] = 1,
	["CreateClientConVar(pp_colormod,0,true,false) [lua/postprocess/color_modify.lua:9]"] = 1,
	["CreateClientConVar(pp_colormod_addr,0,true,false) [lua/postprocess/color_modify.lua:10]"] = 1,
	["CreateClientConVar(pp_colormod_addg,0,true,false) [lua/postprocess/color_modify.lua:11]"] = 1,
	["CreateClientConVar(pp_colormod_addb,0,true,false) [lua/postprocess/color_modify.lua:12]"] = 1,
	["CreateClientConVar(pp_colormod_brightness,0,true,false) [lua/postprocess/color_modify.lua:13]"] = 1,
	["CreateClientConVar(pp_colormod_contrast,1,true,false) [lua/postprocess/color_modify.lua:14]"] = 1,
	["CreateClientConVar(pp_colormod_color,1,true,false) [lua/postprocess/color_modify.lua:15]"] = 1,
	["CreateClientConVar(pp_colormod_mulr,0,true,false) [lua/postprocess/color_modify.lua:16]"] = 1,
	["CreateClientConVar(pp_colormod_mulg,0,true,false) [lua/postprocess/color_modify.lua:17]"] = 1,
	["CreateClientConVar(pp_colormod_mulb,0,true,false) [lua/postprocess/color_modify.lua:18]"] = 1,
	["CreateClientConVar(pp_dof,0,true,false) [lua/postprocess/dof.lua:2]"] = 1,
	["CreateClientConVar(pp_dof_initlength,256,true,false) [lua/postprocess/dof.lua:3]"] = 1,
	["CreateClientConVar(pp_dof_spacing,512,true,false) [lua/postprocess/dof.lua:4]"] = 1,
	["CreateClientConVar(pp_fb,0,true,false) [lua/postprocess/frame_blend.lua:49]"] = 1,
	["CreateClientConVar(pp_fb_frames,16,true,false) [lua/postprocess/frame_blend.lua:54]"] = 1,
	["CreateClientConVar(pp_fb_shutter,0.5,true,false) [lua/postprocess/frame_blend.lua:60]"] = 1,
	["CreateClientConVar(pp_motionblur,0,true,false) [lua/postprocess/motion_blur.lua:9]"] = 1,
	["CreateClientConVar(pp_motionblur_addalpha,0.2,true,false) [lua/postprocess/motion_blur.lua:10]"] = 1,
	["CreateClientConVar(pp_motionblur_drawalpha,0.99,true,false) [lua/postprocess/motion_blur.lua:11]"] = 1,
	["CreateClientConVar(pp_motionblur_delay,0.05,true,false) [lua/postprocess/motion_blur.lua:12]"] = 1,
	["CreateClientConVar(pp_mat_overlay,,true,false) [lua/postprocess/overlay.lua:5]"] = 1,
	["CreateClientConVar(pp_mat_overlay_refractamount,0.3,true,false) [lua/postprocess/overlay.lua:6]"] = 1,
	["CreateClientConVar(pp_sharpen_contrast,1,true,false) [lua/postprocess/sharpen.lua:8]"] = 1,
	["CreateClientConVar(pp_sharpen_distance,1,true,false) [lua/postprocess/sharpen.lua:9]"] = 1,
	["CreateClientConVar(pp_sharpen,0,true,false) [lua/postprocess/sharpen.lua:10]"] = 1,
	["CreateClientConVar(pp_sobel_threshold,0.11,true,false) [lua/postprocess/sobel.lua:6]"] = 1,
	["CreateClientConVar(pp_sobel,0,true,false) [lua/postprocess/sobel.lua:7]"] = 1,
	["CreateClientConVar(pp_stereoscopy,0,true,false) [lua/postprocess/stereoscopy.lua:5]"] = 1,
	["CreateClientConVar(pp_stereoscopy_size,6,true,false) [lua/postprocess/stereoscopy.lua:6]"] = 1,
	["CreateClientConVar(pp_sunbeams_darken,0.95,true,false) [lua/postprocess/sunbeams.lua:9]"] = 1,
	["CreateClientConVar(pp_sunbeams_multiply,1.0,true,false) [lua/postprocess/sunbeams.lua:10]"] = 1,
	["CreateClientConVar(pp_sunbeams_sunsize,0.075,true,false) [lua/postprocess/sunbeams.lua:11]"] = 1,
	["CreateClientConVar(pp_texturize,,true,false) [lua/postprocess/texturize.lua:6]"] = 1,
	["CreateClientConVar(pp_texturize_scale,1,true,false) [lua/postprocess/texturize.lua:7]"] = 1,
	["CreateClientConVar(pp_toytown_passes,3,true,false) [lua/postprocess/toytown.lua:9]"] = 1,
	["CreateClientConVar(pp_toytown_size,0.4,true,false) [lua/postprocess/toytown.lua:10]"] = 1,
	["CreateClientConVar(cl_crosshair_color,0 255 0 100,true,true) [addons/cs guns/lua/weapons/cse_base/cl_init.lua:113]"] = 1,
	["CreateClientConVar(rtcamera_draw,0,false,false) [addons/re-located stools/lua/weapons/gmod_tool/stools/rtcamera.lua:139]"] = 1,
	["CreateClientConVar(cl_showhints,1,1,false) [gamemodes/sandbox/gamemode/cl_hints.lua:3]"] = 1,
	["CreateClientConVar(finger_restrict,1,false,false) [lua/vgui/fingervar.lua:3]"] = 1,
	["CreateClientConVar(ZLib_Installed,0,false,true) [addons/adv duplicator/lua/autorun/shared/dupeshare.lua:17]"] = 1,
	["CreateClientConVar(spp_delay,120,false,true) [addons/spp/lua/spropprotection/cl_init.lua:18]"] = 1,
	["CreateClientConVar(spp_dae,0,false,true) [addons/spp/lua/spropprotection/cl_init.lua:17]"] = 1,
	["CreateClientConVar(spp_dpd,1,false,true) [addons/spp/lua/spropprotection/cl_init.lua:16]"] = 1,
	["CreateClientConVar(spp_awp,1,false,true) [addons/spp/lua/spropprotection/cl_init.lua:15]"] = 1,
	["CreateClientConVar(spp_pgr,1,false,true) [addons/spp/lua/spropprotection/cl_init.lua:14]"] = 1,
	["CreateClientConVar(spp_edmg,1,false,true) [addons/spp/lua/spropprotection/cl_init.lua:13]"] = 1,
	["CreateClientConVar(spp_use,1,false,true) [addons/spp/lua/spropprotection/cl_init.lua:12]"] = 1,
	["CreateClientConVar(spp_admin,1,false,true) [addons/spp/lua/spropprotection/cl_init.lua:11]"] = 1,
	["CreateClientConVar(spp_check,1,false,true) [addons/spp/lua/spropprotection/cl_init.lua:10]"] = 1,
	["CreateClientConVar(cl_screenwater,1,false,false) [addons/hex's server plugins/lua/hsp/gfx/cl_screenwater.lua:7]"] = 1,
	["CreateClientConVar(hsp_spawn_speed,0.6,false,false) [addons/hex's server plugins/lua/hsp/deathmatch/sh_spawneffect.lua:31]"] = 1,
	["CreateClientConVar(hsp_spawn_particles,1,false,false) [addons/hex's server plugins/lua/hsp/deathmatch/sh_spawneffect.lua:30]"] = 1,
	["CreateClientConVar(effects_unfreeze,1,true,false) [gamemodes/sandbox/entities/effects/phys_unfreeze.lua:2]"] = 1,
	["CreateClientConVar(effects_freeze,1,true,false) [gamemodes/sandbox/entities/effects/phys_freeze.lua:2]"] = 1,
	["CreateClientConVar(hsp_gibs_blood,1,true,false) [addons/hex's server plugins/lua/effects/gib_emitter/init.lua:4]"] = 1,
	["CreateClientConVar(hsp_gibs_num,10,true,false) [addons/hex's server plugins/lua/effects/gib_emitter/init.lua:3]"] = 1,
	["CreateClientConVar(hsp_gibs_time,6,true,false) [addons/hex's server plugins/lua/effects/gib_bodypart/init.lua:3]"] = 1,
	["CreateClientConVar(twitch_aim_hidecrosshair,0,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:20]"] = 1,
	["CreateClientConVar(twitch_aim_hidehud,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:19]"] = 1,
	["CreateClientConVar(twitch_hidehud,0,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:18]"] = 1,
	["CreateClientConVar(twitch_aim_bullettime_colourdrain,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:16]"] = 1,
	["CreateClientConVar(twitch_aim_sensitivity,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:8]"] = 1,
	["CreateClientConVar(twitch_tracerfreq,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:7]"] = 1,
	["CreateClientConVar(twitch_aim_hidecrosshair,0,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:20]"] = 1,
	["CreateClientConVar(twitch_aim_hidehud,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:19]"] = 1,
	["CreateClientConVar(twitch_hidehud,0,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:18]"] = 1,
	["CreateClientConVar(twitch_aim_bullettime_colourdrain,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:16]"] = 1,
	["CreateClientConVar(twitch_aim_sensitivity,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:8]"] = 1,
	["CreateClientConVar(twitch_tracerfreq,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:7]"] = 1,
	["CreateClientConVar(twitch_aim_hidecrosshair,0,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:20]"] = 1,
	["CreateClientConVar(twitch_aim_hidehud,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:19]"] = 1,
	["CreateClientConVar(twitch_hidehud,0,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:18]"] = 1,
	["CreateClientConVar(twitch_aim_bullettime_colourdrain,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:16]"] = 1,
	["CreateClientConVar(twitch_aim_sensitivity,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:8]"] = 1,
	["CreateClientConVar(twitch_tracerfreq,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:7]"] = 1,
	["CreateClientConVar(twitch_aim_hidecrosshair,0,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:20]"] = 1,
	["CreateClientConVar(twitch_aim_hidehud,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:19]"] = 1,
	["CreateClientConVar(twitch_hidehud,0,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:18]"] = 1,
	["CreateClientConVar(twitch_aim_bullettime_colourdrain,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:16]"] = 1,
	["CreateClientConVar(twitch_aim_sensitivity,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:8]"] = 1,
	["CreateClientConVar(twitch_tracerfreq,1,true,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:7]"] = 1,
	["CreateClientConVar(mad_crosshair_t,1,true,false) [addons/mad c4/lua/weapons/weapon_mad_base/cl_init.lua:64]"] = 1,
	["CreateClientConVar(mad_crosshair_l,30,true,false) [addons/mad c4/lua/weapons/weapon_mad_base/cl_init.lua:63]"] = 1,
	["CreateClientConVar(mad_crosshair_a,200,true,false) [addons/mad c4/lua/weapons/weapon_mad_base/cl_init.lua:62]"] = 1,
	["CreateClientConVar(mad_crosshair_b,255,true,false) [addons/mad c4/lua/weapons/weapon_mad_base/cl_init.lua:61]"] = 1,
	["CreateClientConVar(mad_crosshair_g,255,true,false) [addons/mad c4/lua/weapons/weapon_mad_base/cl_init.lua:60]"] = 1,
	["CreateClientConVar(mad_crosshair_r,255,true,false) [addons/mad c4/lua/weapons/weapon_mad_base/cl_init.lua:59]"] = 1,
	["CreateClientConVar(crosshair_scale,1,true,false) [addons/koth weapons/lua/weapons/kh_base/shared.lua:382]"] = 1,
	["CreateClientConVar(crosshair_a,255,true,false) [addons/koth weapons/lua/weapons/kh_base/shared.lua:381]"] = 1,
	["CreateClientConVar(crosshair_b,255,true,false) [addons/koth weapons/lua/weapons/kh_base/shared.lua:380]"] = 1,
	["CreateClientConVar(crosshair_g,255,true,false) [addons/koth weapons/lua/weapons/kh_base/shared.lua:379]"] = 1,
	["CreateClientConVar(crosshair_r,255,true,false) [addons/koth weapons/lua/weapons/kh_base/shared.lua:378]"] = 1,
	["CreateClientConVar(gmod_toolmode,rope,true,true) [gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:3]"] = 1,
	["CreateClientConVar(gmod_drawhelp,1,true,false) [gamemodes/sandbox/entities/weapons/gmod_tool/cl_init.lua:2]"] = 1,
	["CreateClientConVar(cl_showhints,1,true,false) [gamemodes/sandbox/gamemode/cl_hints.lua:3]"] = 1,
	["CreateClientConVar(tooltip_delay,0.5,true,false) [lua/vgui/dtooltip.lua:13]"] = 1,
	["CreateClientConVar(pp_toytown,0,true,false) [lua/postprocess/toytown.lua:8]"] = 1,
	["CreateClientConVar(pp_sunbeams,0,true,false) [lua/postprocess/sunbeams.lua:8]"] = 1,
	["CreateClientConVar(pp_bloom,0,true,false) [lua/postprocess/bloom.lua:16]"] = 1,
	["CreateClientConVar(uh_rings,1,true,true) [addons/hex's server plugins/lua/hsp/gfx/cl_rings.lua:7]"] = 1,
	["CreateClientConVar(uh_nametags,1,true,false) [addons/hex's server plugins/lua/hsp/gfx/cl_nametags.lua:8]"] = 1,
	["CreateClientConVar(hsp_stopsounds_auto,0,true,true) [addons/hex's server plugins/lua/hsp/general/cl_stopsounds.lua:7]"] = 1,
},


White_CCV = {
	["CreateConVar(gmod_npcweapon,,128,,nil) [gamemodes/sandbox/gamemode/spawnmenu/creationmenu/content/contenticon.lua:254]"] = 1,
	["CreateConVar(cl_drawthrusterseffects,1,nil,nil) [gamemodes/sandbox/entities/entities/gmod_thruster.lua:13]"] = 1,
	["CreateConVar(cl_draweffectrings,1,0,Should the effect green rings be visible?) [gamemodes/base/entities/entities/prop_effect.lua:5]"] = 1,
	["CreateConVar(cl_drawspawneffect,1,128,,nil) [gamemodes/sandbox/entities/effects/propspawn.lua:3]"] = 1,
	["CreateConVar(cl_drawcameras,1,nil,nil) [addons/re-located stools/lua/entities/gmod_rtcameraprop/cl_init.lua:2]"] = 1,
	["CreateConVar(cl_drawcameras,1,0,Should the cameras be visible?) [gamemodes/sandbox/entities/entities/gmod_cameraprop.lua:5]"] = 1,
	["CreateConVar(twitch_aim_infiniteammo,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:17]"] = 1,
	["CreateConVar(twitch_aim_bullettime_tracers,1,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:15]"] = 1,
	["CreateConVar(twitch_aim_bullettime_timescale,0.2,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:14]"] = 1,
	["CreateConVar(twitch_aim_bullettime_onjump,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:13]"] = 1,
	["CreateConVar(twitch_aim_bullettime,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:12]"] = 1,
	["CreateConVar(twitch_quickdraw,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:11]"] = 1,
	["CreateConVar(twitch_damagemul,1,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:10]"] = 1,
	["CreateConVar(twitch_recoilmul,0.2,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_subsnip/shared.lua:9]"] = 1,
	["CreateConVar(twitch_aim_infiniteammo,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:17]"] = 1,
	["CreateConVar(twitch_aim_bullettime_tracers,1,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:15]"] = 1,
	["CreateConVar(twitch_aim_bullettime_timescale,0.2,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:14]"] = 1,
	["CreateConVar(twitch_aim_bullettime_onjump,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:13]"] = 1,
	["CreateConVar(twitch_aim_bullettime,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:12]"] = 1,
	["CreateConVar(twitch_quickdraw,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:11]"] = 1,
	["CreateConVar(twitch_damagemul,1,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:10]"] = 1,
	["CreateConVar(twitch_recoilmul,0.2,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base_sniper/shared.lua:9]"] = 1,
	["CreateConVar(twitch_aim_infiniteammo,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:17]"] = 1,
	["CreateConVar(twitch_aim_bullettime_tracers,1,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:15]"] = 1,
	["CreateConVar(twitch_aim_bullettime_timescale,0.2,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:14]"] = 1,
	["CreateConVar(twitch_aim_bullettime_onjump,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:13]"] = 1,
	["CreateConVar(twitch_aim_bullettime,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:12]"] = 1,
	["CreateConVar(twitch_quickdraw,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:11]"] = 1,
	["CreateConVar(twitch_damagemul,1,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:10]"] = 1,
	["CreateConVar(twitch_recoilmul,0.2,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base1/shared.lua:9]"] = 1,
	["CreateConVar(twitch_aim_infiniteammo,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:17]"] = 1,
	["CreateConVar(twitch_aim_bullettime_tracers,1,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:15]"] = 1,
	["CreateConVar(twitch_aim_bullettime_timescale,0.2,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:14]"] = 1,
	["CreateConVar(twitch_aim_bullettime_onjump,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:13]"] = 1,
	["CreateConVar(twitch_aim_bullettime,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:12]"] = 1,
	["CreateConVar(twitch_quickdraw,0,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:11]"] = 1,
	["CreateConVar(twitch_damagemul,1,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:10]"] = 1,
	["CreateConVar(twitch_recoilmul,0.2,128,,nil) [addons/twitch weaponry/lua/weapons/weapon_twitch_base/shared.lua:9]"] = 1,
	["CreateConVar(mad_damagemul,1,128,,nil) [addons/mad c4/lua/weapons/weapon_mad_base/shared.lua:13]"] = 1,
	["CreateConVar(mad_recoilmul,1,128,,nil) [addons/mad c4/lua/weapons/weapon_mad_base/shared.lua:12]"] = 1,
	["CreateConVar(physgun_halo,1,128,,Draw the physics gun halo?) [gamemodes/sandbox/gamemode/cl_init.lua:24]"] = 1,
	["CreateConVar(cl_drawworldtooltips,1,128,,nil) [gamemodes/sandbox/gamemode/cl_worldtips.lua:10]"] = 1,
	["CreateConVar(spawnmenu_border,0.1,128,,nil) [gamemodes/sandbox/gamemode/spawnmenu/spawnmenu.lua:2]"] = 1,
	["CreateConVar(physgun_limited,0,8192,nil) [gamemodes/sandbox/gamemode/shared.lua:45]"] = 1,
	["CreateConVar(cl_weaponcolor,0.30 1.80 2.10,131072,,The value is a Vector - so between 0-1 - not between 0-255) [gamemodes/sandbox/gamemode/player_class/player_sandbox.lua:8]"] = 1,
	["CreateConVar(cl_playercolor,0.24 0.34 0.41,131072,,The value is a Vector - so between 0-1 - not between 0-255) [gamemodes/sandbox/gamemode/player_class/player_sandbox.lua:7]"] = 1,
	["CreateConVar(pp_motionblur_delay,0.0,131072,,nil) [lua/postprocess/motion_blur.lua:14]"] = 1,
	["CreateConVar(pp_motionblur_drawalpha,0.99,131072,,nil) [lua/postprocess/motion_blur.lua:13]"] = 1,
	["CreateConVar(pp_motionblur_addalpha,0.2,131072,,nil) [lua/postprocess/motion_blur.lua:12]"] = 1,
	["CreateConVar(pp_motionblur,0,131072,,nil) [lua/postprocess/motion_blur.lua:11]"] = 1,
	["CreateConVar(pp_fb_shutter,0.5,131072,,nil) [lua/postprocess/frame_blend.lua:60]"] = 1,
	["CreateConVar(pp_fb_frames,16,131072,,nil) [lua/postprocess/frame_blend.lua:54]"] = 1,
	["CreateConVar(pp_fb,0,131072,,nil) [lua/postprocess/frame_blend.lua:49]"] = 1,
	["CreateConVar(Serialiser_SaveCompressed,0,128,,nil) [addons/adv duplicator/lua/autorun/serialiser.lua:28]"] = 1,
	["CreateConVar(cl_legs,1,128,,Enable/Disable the rendering of the legs) [addons/hex's server plugins/lua/hsp/gfx/cl_legs.lua:10]"] = 1,
	["CreateConVar(hsp_spawn_wait,3.2,8192,,nil) [addons/hex's server plugins/lua/hsp/deathmatch/sh_spawneffect.lua:28]"] = 1,
	["CreateConVar(hsp_spawn_enabled,1,8192,,nil) [addons/hex's server plugins/lua/hsp/deathmatch/sh_spawneffect.lua:27]"] = 1,
	["CreateConVar(cl_legs,1,128,,Enable/Disable the rendering of the legs) [addons/hex's server plugins/lua/hsp/deathmatch/cl_legs.lua:10]"] = 1,
	["CreateConVar(hsp_nofizz_phys,1,8192,,nil) [addons/hex's server plugins/lua/hsp/antispam/sh_nofizz.lua:10]"] = 1,
	["CreateConVar(hsp_nofizz_tool,1,8192,,nil) [addons/hex's server plugins/lua/hsp/antispam/sh_nofizz.lua:9]"] = 1,
	["CreateConVar(hud_deathnotice_time,6,8192,Amount of time to show death notice) [gamemodes/base/gamemode/cl_deathnotice.lua:3]"] = 1,
},


White_PRT = {
	["2469972261"] = 1,
	["2476742495"] = 1,
	["1767216135"] = 1,
	["1875825159"] = 1,
	["147895516"] = 1,
	["3022894561"] = 1,
	["734451819"] = 1,
	["933524113"] = 1,
	["2711015911"] = 1,
	["3933337308"] = 1,
	["3842593408"] = 1,
	["2527171921"] = 1,
	["4063415014"] = 1,
	["1237140527"] = 1,
	["1849154647"] = 1,
	["474954841"] = 1,
	["1038633222"] = 1,
},


}
