

//MOD, MAIN FILES
HAC.SERVER.ECheck_Blacklist = { --Searches any dir (lowercase)

}


//EXACT MATCH, can't add to above list as not always hacks (lowercase)
HAC.SERVER.ECheck_Exact = {

}




//ROOT FILES
HAC.SERVER.ECheck_RootBlacklist = {

}


//Data only
HAC.SERVER.ECheck_Data = { --lowercase, checked AFTER the ban list below!

}

HAC.SERVER.ECheck_Data_BAN = { --Lowercase
	"$w4g",
	"swag_hack",
	"swag_hax",
	"detour/kys",
	"cyanide_",
	"mhake/hvh",
	"anxition/",
	"/rmenu/",
	"/rhook/",
	"/trollhook/",
	"/pax/steal",
	"aimbot/button",
	"aimware.txt",
	"pa$teware",
	"pasteware",
	"nostalgia_hvh",
	"pasteware",
	"memeware.txt",
	"newshack.txt",
	"aimbot_whitelist.txt",
	"snixzz",
	"mythx",
	"/sh/configs",
	"dreambot_",
	"spinsquad",
	"bluebotv",
	"ampris/settings.txt",
	"/d_settings.txt",
	"/nh/default",
	"/cluaview/",
	"nigger",
	"autis",
}






//CMod list, lowercase, ONLY FOR .DLL's
HAC.SERVER.ECheck_CMod = {

}



--- === Whitelist === ---
HAC.SERVER.ECheck_WhiteList = { --Both Low and What
	"lua/vgui/prop_combo.lua",
	"lua/vgui/propselect.lua",
	"lua/vgui/spawnicon.lua",
	"lua/vgui/dtextentry.lua",
	"lua/autorun/properties/npc_scale.lua",
	"lua/vgui/dbinder.lua",
	"lua/vgui/dentityproperties.lua",
	"lua/vgui/dfilebrowser.lua",
	"lua/skins/default.lua",
	"lua/vgui/ddrawer.lua",
	"lua/vgui/dcolorpalette.lua",
	"lua/includes/menu.lua",
	"lua/includes/util.lua",
	"lua/vgui/dgrid.lua",
	"lua/menu/mainmenu.lua",
	"lua/menu/menu_dupe.lua",
	"lua/menu/menu_addon.lua",
	"lua/menu/ugcpublish.lua",
	"lua/vgui/dhtmlcontrols.lua",
	"lua/vgui/dlistbox.lua",
	"lua/vgui/dlistview_column.lua",
	"lua/autorun/server/sensorbones/tf2_pyro_demo.lua",
	"lua/autorun/server/sensorbones/tf2_scout.lua",
	"lua/derma/derma_utils.lua",
	"lua/postprocess/super_dof.lua",
	"lua/vgui/dnumberwang.lua",
	"lua/vgui/dnumpad.lua",
	"lua/vgui/dpaneloverlay.lua",
	"lua/vgui/dmodelselectmulti.lua",
	"lua/vgui/dmenubar.lua",
	"lua/vgui/dmenuoptioncvar.lua",
	"lua/vgui/dpanelselect.lua",
	"lua/vgui/dscrollbargrip.lua",
	"lua/vgui/dverticaldivider.lua",
	"lua/vgui/drgbpicker.lua",
	"lua/vgui/dtooltip.lua",
	"lua/vgui/dslider.lua",
	"lua/vgui/dtilelayout.lua",
	"lua/postprocess/toytown.lua",
	"lua/vgui/matselect.lua",
	"lua/postprocess/motion_blur.lua",
	"lua/includes/extensions/client/panel.lua",
	"lua/includes/extensions/net.lua",
	"lua/includes/extensions/client/player.lua",
	"lua/includes/modules/killicon.lua",
	"lua/includes/extensions/math.lua",
	"lua/includes/modules/team.lua",
	"lua/includes/modules/widget.lua",
	"lua/vgui/dsprite.lua",
	"lua/vgui/diconbrowser.lua",
	"lua/vgui/dlabelurl.lua",
	"lua/includes/util/tooltips.lua",
	"lua/includes/extensions/string.lua",
	"lua/includes/extensions/util.lua",
	"lua/vgui/dsizetocontents.lua",
	"lua/vgui/dproperties.lua",
	"lua/vgui/dlabeleditable.lua",
	"lua/vgui/dnumberscratch.lua",
	"lua/includes/extensions/client/panel/scriptedpanels.lua",
	"lua/vgui/dpanel.lua",
	"lua/vgui/dkillicon.lua",
	"lua/vgui/dlistview_line.lua",
	"lua/vgui/dvscrollbar.lua",
	"lua/includes/modules/cookie.lua",
	"lua/includes/modules/draw.lua",
	"lua/autorun/properties.lua",
	"lua/vgui/vgui_panellist.lua",
	"lua/vgui/slidebar.lua",
	"lua/includes/modules/constraint.lua",
	"lua/vgui/prop_float.lua",
	"lua/vgui/fingerposer.lua",
	"lua/autorun/properties/bodygroups.lua",
	"lua/autorun/properties/remove.lua",
	"lua/includes/modules/ai_task.lua",
	"lua/vgui/dhtml.lua",
	"lua/postprocess/sunbeams.lua",
	"lua/postprocess/sharpen.lua",
	"lua/autorun/properties/keep_upright.lua",
	"lua/drive/drive_sandbox.lua",
	"lua/includes/modules/cleanup.lua",
	"lua/derma/derma_gwen.lua",
	"lua/autorun/properties/skin.lua",
	"lua/includes/modules/halo.lua",
	"lua/vgui/dhorizontalscroller.lua",
	"lua/includes/util/workshop_files.lua",
	"lua/vgui/contextbase.lua",
	"lua/menu/menu_save.lua",
	"lua/includes/init.lua",
	"lua/autorun/developer_functions.lua",
	"lua/includes/modules/spawnmenu.lua",
	"lua/includes/init_menu.lua",
	"lua/includes/modules/menubar.lua",
	"lua/includes/extensions/motionsensor.lua",
	"lua/includes/modules/matproxy.lua",
	"lua/menu/motionsensor.lua",
	"lua/includes/modules/presets.lua",
	"lua/vgui/dhorizontaldivider.lua",
	"lua/menu/openurl.lua",
	"lua/menu/mount/vgui/workshop.lua",
	"lua/vgui/dbubblecontainer.lua",
	"lua/menu/menu.lua",
	"lua/includes/modules/notification.lua",
	"lua/vgui/ddragbase.lua",
	"lua/vgui/dcolumnsheet.lua",
	"lua/postprocess/bokeh_dof.lua",
	"lua/includes/extensions/debug.lua",
	"lua/menu/getmaps.lua",
	"lua/menu/errors.lua",
	"lua/includes/modules/utf8.lua",
	"lua/includes/extensions/game.lua",
	"lua/vgui/dcheckbox.lua",
	"lua/menu/loading.lua",
	"lua/includes/util/client.lua",
	"lua/includes/extensions/file.lua",
	"lua/drive/drive_noclip.lua",
	"lua/autorun/properties/drive.lua",
	"lua/includes/modules/ai_schedule.lua",
	"lua/includes/modules/effects.lua",
	"lua/includes/modules/hook.lua",
	"lua/includes/gmsave/entity_filters.lua",
	"lua/includes/extensions/player_auth.lua",
	"lua/includes/extensions/client/render.lua",
	"lua/includes/extensions/client/entity.lua",
	"lua/includes/gmsave/player.lua",
	"lua/includes/extensions/player.lua",
	"lua/includes/modules/cvars.lua",
	"lua/includes/modules/concommand.lua",
	"lua/includes/extensions/util/worldpicker.lua",
	"lua/includes/modules/duplicator.lua",
	"lua/includes/gmsave/constraints.lua",
	"lua/autorun/menubar.lua",
	"lua/autorun/properties/kinect_controller.lua",
	"lua/menu/mount/mount.lua",
	"lua/menu/background.lua",
	"lua/vgui/material.lua",
	"lua/menu/cef_credits.lua",
	"lua/menu/video.lua",
	"lua/vgui/imagecheckbox.lua",
	"lua/autorun/properties/collisions.lua",
	"lua/autorun/game_hl2.lua",
	"lua/autorun/properties/persist.lua",
	"lua/send.txt",
	"lua/autorun/server/test.lua",
	"lua/vgui/dbutton.lua",
	"lua/vgui/dcolorbutton.lua",
	"lua/vgui/dmenuoption.lua",
	"lua/vgui/dnotify.lua",
	"lua/vgui/dcolorcombo.lua",
	"lua/vgui/dlabel.lua",
	"lua/autorun/base_npcs.lua",
	"lua/vgui/dcolormixer.lua",
	"lua/vgui/dimage.lua",
	"lua/autorun/base_vehicles.lua",
	"lua/postprocess/bloom.lua",
	"lua/vgui/dnumslider.lua",
	"lua/vgui/dpropertysheet.lua",
	"lua/autorun/server/sensorbones/valvebiped.lua",
	"lua/postprocess/stereoscopy.lua",
	"lua/autorun/server/sensorbones/tf2_sniper.lua",
	"lua/autorun/server/sensorbones/tf2_engineer.lua",
	"lua/vgui/dprogress.lua",
	"lua/vgui/dtree_node_button.lua",
	"lua/vgui/dshape.lua",
	"lua/vgui/dalphabar.lua",
	"lua/vgui/dadjustablemodelpanel.lua",
	"lua/vgui/dlistview.lua",
	"lua/menu/demo_to_video.lua",
	"lua/derma/init.lua",
	"lua/includes/extensions/table.lua",
	"lua/derma/derma_animation.lua",
	"lua/includes/modules/drive.lua",
	"lua/derma/derma.lua",
	"lua/includes/modules/controlpanel.lua",
	"lua/includes/vgui_base.lua",
	"lua/includes/extensions/ents.lua",
	"lua/includes/extensions/client/panel/dragdrop.lua",
	"lua/includes/extensions/client/globals.lua",
	"lua/includes/extensions/weapon.lua",
	"lua/includes/modules/construct.lua",
	"lua/includes/extensions/client/panel/selections.lua",
	"lua/includes/extensions/entity.lua",
	"lua/includes/gmsave/physics.lua",
	"lua/includes/modules/baseclass.lua",
	"lua/includes/gmsave.lua",
	"lua/autorun/server/sensorbones/css.lua",
	"lua/includes/modules/scripted_ents.lua",
	"lua/includes/modules/markup.lua",
	"lua/includes/modules/list.lua",
	"lua/includes/util/model_database.lua",
	"lua/includes/util/javascript_util.lua",
	"lua/includes/util/color.lua",
	"lua/matproxy/sky_paint.lua",
	"lua/includes/modules/properties.lua",
	"lua/includes/extensions/vector.lua",
	"lua/autorun/properties/editentity.lua",
	"lua/includes/modules/numpad.lua",
	"lua/vgui/prop_vectorcolor.lua",
	"lua/vgui/prop_generic.lua",
	"lua/vgui/prop_boolean.lua",
	"lua/vgui/fingervar.lua",
	"lua/vgui/prop_int.lua",
	"lua/menu/mount/vgui/addon_rocket.lua",
	"lua/menu/util.lua",
	"lua/vgui/dimagebutton.lua",
	"lua/vgui/dcategorycollapse.lua",
	"lua/vgui/dmodelpanel.lua",
	"lua/vgui/dmodelselect.lua",
	"lua/menu/progressbar.lua",
	"lua/vgui/dtree_node.lua",
	"lua/postprocess/texturize.lua",
	"lua/vgui/dlistlayout.lua",
	"lua/vgui/dcategorylist.lua",
	"lua/vgui/dcombobox.lua",
	"lua/vgui/dframe.lua",
	"lua/vgui/dtree.lua",
	"lua/vgui/diconlayout.lua",
	"lua/vgui/dcolorcube.lua",
	"lua/vgui/dmenu.lua",
	"lua/vgui/dexpandbutton.lua",
	"lua/vgui/dform.lua",
	"lua/vgui/dscrollpanel.lua",
	"lua/vgui/dpanellist.lua",
	"lua/postprocess/overlay.lua",
	"lua/postprocess/sobel.lua",
	"lua/includes/modules/gamemode.lua",
	"lua/derma/derma_example.lua",
	"lua/autorun/server/sensorbones/tf2_spy_solider.lua",
	"lua/includes/modules/http.lua",
	"lua/includes/modules/player_manager.lua",
	"lua/derma/derma_menus.lua",
	"lua/includes/gui/icon_progress.lua",
	"lua/drive/drive_base.lua",
	"lua/includes/extensions/coroutine.lua",
	"lua/includes/extensions/angle.lua",
	"lua/menu/menu_demo.lua",
	"lua/includes/modules/saverestore.lua",
	"lua/autorun/utilities_menu.lua",
	"lua/matproxy/player_color.lua",
	"lua/postprocess/frame_blend.lua",
	"lua/matproxy/player_weapon_color.lua",
	"lua/postprocess/dof.lua",
	"lua/includes/modules/search.lua",
	"lua/includes/util/vgui_showlayout.lua",
	"lua/includes/modules/weapons.lua",
	"lua/includes/util/sql.lua",
	"lua/includes/modules/undo.lua",
	"lua/includes/modules/usermessage.lua",
	"lua/includes/extensions/client/panel/animation.lua",
	"lua/postprocess/color_modify.lua",
	"lua/autorun/client/gm_demo.lua",
	"lua/autorun/client/demo_recording.lua",
	"lua/autorun/properties/bone_manipulate.lua",
	"lua/autorun/properties/ignite.lua",
	"lua/autorun/properties/gravity.lua",
	"lua/autorun/server/sensorbones/tf2_heavy.lua",
	"lua/autorun/server/sensorbones/eli.lua",
	"lua/autorun/properties/statue.lua",
	"lua/autorun/server/sensorbones/tf2_medic.lua",
	"lua/autorun/server/admin_functions.lua",
	"R/chromium.log",
	"R/crashes/a9759121-c7c1-489e-847b-ae120e7c4523.dmp",
	"R/FactoryReset-GMod.bat",
	"R/ThirdPartyLegalNotices.txt",
}


//Do not ban for these! (lowercase)
HAC.SERVER.ECheck_LogOnly = {

}






//Default GMod files, can't override!
HAC.SERVER.ECheck_DefaultFiles = {
--[[	"gamemodes/sandbox/entities/entities/gmod_cameraprop.lua",
	"gamemodes/sandbox/entities/entities/gmod_thruster.lua",
	"gamemodes/sandbox/entities/effects/phys_freeze.lua",
	"gamemodes/sandbox/entities/effects/phys_unfreeze.lua",
	"gamemodes/sandbox/entities/effects/propspawn.lua",
	"gamemodes/base/entities/entities/prop_effect.lua",
	"lua/send.txt",
	"lua/autorun/base_npcs.lua",
	"lua/autorun/base_vehicles.lua",
	"lua/autorun/developer_functions.lua",
	"lua/autorun/game_hl2.lua",
	"lua/autorun/menubar.lua",
	"lua/autorun/properties.lua",
	"lua/autorun/utilities_menu.lua",
	"lua/autorun/client/demo_recording.lua",
	"lua/autorun/client/gm_demo.lua",
	"lua/autorun/properties/bodygroups.lua",
	"lua/autorun/properties/bone_manipulate.lua",
	"lua/autorun/properties/collisions.lua",
	"lua/autorun/properties/drive.lua",
	"lua/autorun/properties/editentity.lua",
	"lua/autorun/properties/gravity.lua",
	"lua/autorun/properties/ignite.lua",
	"lua/autorun/properties/keep_upright.lua",
	"lua/autorun/properties/kinect_controller.lua",
	"lua/autorun/properties/npc_scale.lua",
	"lua/autorun/properties/persist.lua",
	"lua/autorun/properties/remove.lua",
	"lua/autorun/properties/skin.lua",
	"lua/autorun/properties/statue.lua",
	"lua/autorun/server/admin_functions.lua",
	"lua/autorun/server/sensorbones/css.lua",
	"lua/autorun/server/sensorbones/eli.lua",
	"lua/autorun/server/sensorbones/tf2_engineer.lua",
	"lua/autorun/server/sensorbones/tf2_heavy.lua",
	"lua/autorun/server/sensorbones/tf2_medic.lua",
	"lua/autorun/server/sensorbones/tf2_pyro_demo.lua",
	"lua/autorun/server/sensorbones/tf2_scout.lua",
	"lua/autorun/server/sensorbones/tf2_sniper.lua",
	"lua/autorun/server/sensorbones/tf2_spy_solider.lua",
	"lua/autorun/server/sensorbones/valvebiped.lua",
	"lua/derma/derma.lua",
	"lua/derma/derma_animation.lua",
	"lua/derma/derma_example.lua",
	"lua/derma/derma_gwen.lua",
	"lua/derma/derma_menus.lua",
	"lua/derma/derma_utils.lua",
	"lua/derma/init.lua",
	"lua/drive/drive_base.lua",
	"lua/drive/drive_noclip.lua",
	"lua/drive/drive_sandbox.lua",
	"lua/entities/sent_ball.lua",
	"lua/entities/widget_arrow.lua",
	"lua/entities/widget_axis.lua",
	"lua/entities/widget_base.lua",
	"lua/entities/widget_bones.lua",
	"lua/entities/widget_disc.lua",
	"lua/includes/dev_server_test.lua",
	"lua/includes/gmsave.lua",
	"lua/includes/init.lua",
	"lua/includes/init_menu.lua",
	"lua/includes/menu.lua",
	"lua/includes/util.lua",
	"lua/includes/vgui_base.lua",
	"lua/includes/extensions/angle.lua",
	"lua/includes/extensions/coroutine.lua",
	"lua/includes/extensions/debug.lua",
	"lua/includes/extensions/entity.lua",
	"lua/includes/extensions/ents.lua",
	"lua/includes/extensions/file.lua",
	"lua/includes/extensions/game.lua",
	"lua/includes/extensions/math.lua",
	"lua/includes/extensions/motionsensor.lua",
	"lua/includes/extensions/player.lua",
	"lua/includes/extensions/player_auth.lua",
	"lua/includes/extensions/string.lua",
	"lua/includes/extensions/table.lua",
	"lua/includes/extensions/util.lua",
	"lua/includes/extensions/vector.lua",
	"lua/includes/extensions/weapon.lua",
	"lua/includes/extensions/client/entity.lua",
	"lua/includes/extensions/client/globals.lua",
	"lua/includes/extensions/client/panel.lua",
	"lua/includes/extensions/client/player.lua",
	"lua/includes/extensions/client/render.lua",
	"lua/includes/extensions/client/panel/animation.lua",
	"lua/includes/extensions/client/panel/dragdrop.lua",
	"lua/includes/extensions/client/panel/scriptedpanels.lua",
	"lua/includes/extensions/client/panel/selections.lua",
	"lua/includes/extensions/util/worldpicker.lua",
	"lua/includes/gmsave/constraints.lua",
	"lua/includes/gmsave/entity_filters.lua",
	"lua/includes/gmsave/physics.lua",
	"lua/includes/gmsave/player.lua",
	"lua/includes/gui/icon_progress.lua",
	"lua/includes/modules/ai_schedule.lua",
	"lua/includes/modules/ai_task.lua",
	"lua/includes/modules/baseclass.lua",
	"lua/includes/modules/cleanup.lua",
	"lua/includes/modules/concommand.lua",
	"lua/includes/modules/constraint.lua",
	"lua/includes/modules/construct.lua",
	"lua/includes/modules/controlpanel.lua",
	"lua/includes/modules/cookie.lua",
	"lua/includes/modules/cvars.lua",
	"lua/includes/modules/draw.lua",
	"lua/includes/modules/drive.lua",
	"lua/includes/modules/duplicator.lua",
	"lua/includes/modules/effects.lua",
	"lua/includes/modules/gamemode.lua",
	"lua/includes/modules/halo.lua",
	"lua/includes/modules/hook.lua",
	"lua/includes/modules/http.lua",
	"lua/includes/modules/killicon.lua",
	"lua/includes/modules/list.lua",
	"lua/includes/modules/markup.lua",
	"lua/includes/modules/matproxy.lua",
	"lua/includes/modules/menubar.lua",
	"lua/includes/extensions/net.lua",
	"lua/includes/modules/notification.lua",
	"lua/includes/modules/numpad.lua",
	"lua/includes/modules/player_manager.lua",
	"lua/includes/modules/presets.lua",
	"lua/includes/modules/properties.lua",
	"lua/includes/modules/saverestore.lua",
	"lua/includes/modules/scripted_ents.lua",
	"lua/includes/modules/search.lua",
	"lua/includes/modules/spawnmenu.lua",
	"lua/includes/modules/team.lua",
	"lua/includes/modules/undo.lua",
	"lua/includes/modules/usermessage.lua",
	"lua/includes/modules/weapons.lua",
	"lua/includes/modules/widget.lua",
	"lua/includes/util/client.lua",
	"lua/includes/util/entity_creation_helpers.lua",
	"lua/includes/util/javascript_util.lua",
	"lua/includes/util/model_database.lua",
	"lua/includes/util/sql.lua",
	"lua/includes/util/tooltips.lua",
	"lua/includes/util/vgui_showlayout.lua",
	"lua/includes/util/workshop_files.lua",
	"lua/matproxy/player_color.lua",
	"lua/matproxy/player_weapon_color.lua",
	"lua/matproxy/sky_paint.lua",
	"lua/menu/background.lua",
	"lua/menu/demo_to_video.lua",
	"lua/menu/errors.lua",
	"lua/menu/getmaps.lua",
	"lua/menu/loading.lua",
	"lua/menu/mainmenu.lua",
	"lua/menu/menu.lua",
	"lua/menu/menu_addon.lua",
	"lua/menu/menu_demo.lua",
	"lua/menu/menu_dupe.lua",
	"lua/menu/menu_save.lua",
	"lua/menu/motionsensor.lua",
	"lua/menu/progressbar.lua",
	"lua/menu/video.lua",
	"lua/menu/mount/mount.lua",
	"lua/menu/mount/vgui/addon_rocket.lua",
	"lua/menu/mount/vgui/workshop.lua",
	"lua/postprocess/bloom.lua",
	"lua/postprocess/bokeh_dof.lua",
	"lua/postprocess/color_modify.lua",
	"lua/postprocess/dof.lua",
	"lua/postprocess/frame_blend.lua",
	"lua/postprocess/motion_blur.lua",
	"lua/postprocess/overlay.lua",
	"lua/postprocess/sharpen.lua",
	"lua/postprocess/sobel.lua",
	"lua/postprocess/stereoscopy.lua",
	"lua/postprocess/sunbeams.lua",
	"lua/postprocess/super_dof.lua",
	"lua/postprocess/texturize.lua",
	"lua/postprocess/toytown.lua",
	"lua/skins/default.lua",
	"lua/vgui/contextbase.lua",
	"lua/vgui/dadjustablemodelpanel.lua",
	"lua/vgui/dalphabar.lua",
	"lua/vgui/dbinder.lua",
	"lua/vgui/dbubblecontainer.lua",
	"lua/vgui/dbutton.lua",
	"lua/vgui/dcategorycollapse.lua",
	"lua/vgui/dcategorylist.lua",
	"lua/vgui/dcheckbox.lua",
	"lua/vgui/dcolorbutton.lua",
	"lua/vgui/dcolorcombo.lua",
	"lua/vgui/dcolorcube.lua",
	"lua/vgui/dcolormixer.lua",
	"lua/vgui/dcolorpalette.lua",
	"lua/vgui/dcolumnsheet.lua",
	"lua/vgui/dcombobox.lua",
	"lua/vgui/ddragbase.lua",
	"lua/vgui/ddrawer.lua",
	"lua/vgui/dentityproperties.lua",
	"lua/vgui/dexpandbutton.lua",
	"lua/vgui/dfilebrowser.lua",
	"lua/vgui/dform.lua",
	"lua/vgui/dframe.lua",
	"lua/vgui/dgrid.lua",
	"lua/vgui/dhorizontaldivider.lua",
	"lua/vgui/dhorizontalscroller.lua",
	"lua/vgui/dhtml.lua",
	"lua/vgui/dhtmlcontrols.lua",
	"lua/vgui/diconbrowser.lua",
	"lua/vgui/diconlayout.lua",
	"lua/vgui/dimage.lua",
	"lua/vgui/dimagebutton.lua",
	"lua/vgui/dkillicon.lua",
	"lua/vgui/dlabel.lua",
	"lua/vgui/dlabeleditable.lua",
	"lua/vgui/dlabelurl.lua",
	"lua/vgui/dlistbox.lua",
	"lua/vgui/dlistlayout.lua",
	"lua/vgui/dlistview.lua",
	"lua/vgui/dlistview_column.lua",
	"lua/vgui/dlistview_line.lua",
	"lua/vgui/dmenu.lua",
	"lua/vgui/dmenubar.lua",
	"lua/vgui/dmenuoption.lua",
	"lua/vgui/dmenuoptioncvar.lua",
	"lua/vgui/dmodelpanel.lua",
	"lua/vgui/dmodelselect.lua",
	"lua/vgui/dmodelselectmulti.lua",
	"lua/vgui/dnotify.lua",
	"lua/vgui/dnumberscratch.lua",
	"lua/vgui/dnumberwang.lua",
	"lua/vgui/dnumpad.lua",
	"lua/vgui/dnumslider.lua",
	"lua/vgui/dpanel.lua",
	"lua/vgui/dpanellist.lua",
	"lua/vgui/dpaneloverlay.lua",
	"lua/vgui/dpanelselect.lua",
	"lua/vgui/dprogress.lua",
	"lua/vgui/dproperties.lua",
	"lua/vgui/dpropertysheet.lua",
	"lua/vgui/drgbpicker.lua",
	"lua/vgui/dscrollbargrip.lua",
	"lua/vgui/dscrollpanel.lua",
	"lua/vgui/dshape.lua",
	"lua/vgui/dsizetocontents.lua",
	"lua/vgui/dslider.lua",
	"lua/vgui/dsprite.lua",
	"lua/vgui/dtextentry.lua",
	"lua/vgui/dtilelayout.lua",
	"lua/vgui/dtooltip.lua",
	"lua/vgui/dtree.lua",
	"lua/vgui/dtree_node.lua",
	"lua/vgui/dtree_node_button.lua",
	"lua/vgui/dverticaldivider.lua",
	"lua/vgui/dvscrollbar.lua",
	"lua/vgui/fingerposer.lua",
	"lua/vgui/fingervar.lua",
	"lua/vgui/imagecheckbox.lua",
	"lua/vgui/material.lua",
	"lua/vgui/matselect.lua",
	"lua/vgui/prop_boolean.lua",
	"lua/vgui/prop_float.lua",
	"lua/vgui/prop_generic.lua",
	"lua/vgui/prop_int.lua",
	"lua/vgui/prop_vectorcolor.lua",
	"lua/vgui/propselect.lua",
	"lua/vgui/slidebar.lua",
	"lua/vgui/spawnicon.lua",
	"lua/vgui/vgui_panellist.lua",
	"lua/weapons/flechette_gun.lua",
	"lua/weapons/weapon_fists.lua",
	"lua/weapons/weapon_medkit.lua",]]
}





concommand.Add("ec_reload", function(self)
	self:print("! Reloading ECheck")
	include("lists/sv_echeck.lua")
end)




